Ruby: ext/rbconfig/sizeof/sizes.c File Reference
sizes.c File Reference
#include "ruby/ruby.h"
Macros
#define DEFINE(type, size) rb_hash_aset(s, rb_str_new_cstr(#type), INT2FIX(SIZEOF_##size))
#define DEFINE_SIZE(type) rb_hash_aset(s, rb_str_new_cstr(#type), INT2FIX(sizeof(type)))
Functions
void Init_limits (void)
void Init_sizeof (void)
Macro Definition Documentation
DEFINE
#define DEFINE (type, size) rb_hash_aset(s, rb_str_new_cstr(#type), INT2FIX(SIZEOF_##size))
Referenced by Init_sizeof().
DEFINE_SIZE
#define DEFINE_SIZE (type) rb_hash_aset(s, rb_str_new_cstr(#type), INT2FIX(sizeof(type)))
Referenced by Init_sizeof().
Function Documentation
Init_limits()
void Init_limits (void)
Definition at line 14 of file limits.c.
References DEFINE, FIXNUM_MAX, FIXNUM_MIN, LONG_MAX, LONG_MIN, MAX2NUM, MIN2NUM, rb_define_const(), rb_define_module(), and rb_hash_new().
Referenced by Init_sizeof().
Init_sizeof()
void Init_sizeof (void)
Definition at line 13 of file sizes.c.
References DEFINE, DEFINE_SIZE, Init_limits(), OBJ_FREEZE, off_t, rb_define_const(), rb_define_module(), and rb_hash_new().