Ruby: safe.c File Reference
safe.c File Reference
#include "ruby/ruby.h"
#include "vm_core.h"
Macros
#define SAFE_LEVEL_MAX RUBY_SAFE_LEVEL_MAX
Functions
int ruby_safe_level_2_warning (void)
int rb_safe_level (void)
void rb_set_safe_level_force (int safe)
void rb_set_safe_level (int level)
void rb_secure (int level)
void rb_secure_update (VALUE obj)
void rb_insecure_operation (void)
void rb_check_safe_obj (VALUE x)
void Init_safe (void)
Macro Definition Documentation
SAFE_LEVEL_MAX
#define SAFE_LEVEL_MAX RUBY_SAFE_LEVEL_MAX
Definition at line 17 of file safe.c.
Referenced by rb_set_safe_level().
Function Documentation
Init_safe()
void Init_safe (void)
Definition at line 125 of file safe.c.
References rb_define_virtual_variable().
rb_check_safe_obj()
void rb_check_safe_obj (VALUE x)
Definition at line 117 of file safe.c.
References OBJ_TAINTED, rb_insecure_operation(), and rb_safe_level().
rb_insecure_operation()
void rb_insecure_operation (void)
Definition at line 104 of file safe.c.
References PRIsVALUE, rb_eSecurityError, rb_frame_callee(), rb_id2str, and rb_raise().
Referenced by rb_check_safe_obj(), and rb_get_path_check_to_string().
rb_safe_level()
int rb_safe_level (void)
Definition at line 35 of file safe.c.
References GET_THREAD.
Referenced by rb_check_copyable(), rb_check_safe_obj(), rb_eval_cmd(), rb_exec_end_proc(), rb_f_require(), rb_f_require_relative(), rb_find_file(), rb_find_file_ext(), rb_get_path(), rb_method_call_with_block(), rb_require(), rb_require_internal(), and rb_secure().
rb_secure()
void rb_secure (int level)
Definition at line 83 of file safe.c.
References PRIsVALUE, rb_eSecurityError, rb_frame_callee(), rb_id2str, rb_raise(), and rb_safe_level().
Referenced by rb_iseq_disasm().
rb_secure_update()
void rb_secure_update (VALUE obj)
Definition at line 99 of file safe.c.
rb_set_safe_level()
void rb_set_safe_level (int level)
Definition at line 47 of file safe.c.
References rb_thread_struct::ec, GET_THREAD, level, rb_eArgError, rb_raise(), rb_execution_context_struct::safe_level, and SAFE_LEVEL_MAX.
rb_set_safe_level_force()
void rb_set_safe_level_force (int safe)
Definition at line 41 of file safe.c.
References GET_THREAD.
Referenced by rb_eval_cmd(), rb_method_call_with_block(), and rb_require_internal().
ruby_safe_level_2_warning()
int ruby_safe_level_2_warning (void)
Definition at line 29 of file safe.c.