Ruby: localeinit.c File Reference
localeinit.c File Reference
#include "internal.h"
#include "encindex.h"
Macros
#define NO_LOCALE_CHARMAP 1
Functions
VALUE rb_locale_charmap (VALUE klass)
int rb_locale_charmap_index (void)
int Init_enc_set_filesystem_encoding (void)
Macro Definition Documentation
NO_LOCALE_CHARMAP
#define NO_LOCALE_CHARMAP 1
Definition at line 32 of file localeinit.c.
Function Documentation
Init_enc_set_filesystem_encoding()
int Init_enc_set_filesystem_encoding (void)
Definition at line 118 of file localeinit.c.
References ENCINDEX_ASCII, ENCINDEX_US_ASCII, ENCINDEX_UTF_8, rb_default_external_encoding(), rb_enc_find_index(), and rb_enc_to_index().
rb_locale_charmap()
VALUE rb_locale_charmap (VALUE klass)
Definition at line 90 of file localeinit.c.
References name, rb_enc_find_index(), and rb_usascii_str_new_cstr().
rb_locale_charmap_index()
int rb_locale_charmap_index (void)
Definition at line 108 of file localeinit.c.
References ENCINDEX_US_ASCII.