Ruby: ext/socket/ifaddr.c File Reference
ifaddr.c File Reference
#include "rubysocket.h"
Macros
#define socket_s_getifaddrs rb_f_notimplement
Functions
void rsock_init_sockifaddr (void)
Macro Definition Documentation
socket_s_getifaddrs
#define socket_s_getifaddrs rb_f_notimplement
Definition at line 456 of file ifaddr.c.
Referenced by rsock_init_sockifaddr().
Function Documentation
rsock_init_sockifaddr()
void rsock_init_sockifaddr (void)
Definition at line 460 of file ifaddr.c.
References rb_cData, rb_cSocket, rb_define_class_under(), rb_define_method(), rb_define_singleton_method(), and socket_s_getifaddrs.
Referenced by rsock_init_socket_init().