Ruby: ext/win32ole/win32ole_variable.c File Reference
win32ole_variable.c File Reference
#include "win32ole.h"
Data Structures
struct olevariabledata
Functions
VALUE create_win32ole_variable (ITypeInfo *pTypeInfo, UINT index, VALUE name)
void Init_win32ole_variable (void)
Function Documentation
create_win32ole_variable()
VALUE create_win32ole_variable (ITypeInfo * pTypeInfo, UINT index, VALUE name)
Definition at line 52 of file win32ole_variable.c.
References cWIN32OLE_VARIABLE, olevariabledata::index, name, OLE_ADDREF, olevariabledata::pTypeInfo, rb_intern, rb_ivar_set(), and TypedData_Make_Struct.
Init_win32ole_variable()
void Init_win32ole_variable (void)
Definition at line 368 of file win32ole_variable.c.
References cWIN32OLE_VARIABLE, rb_cObject, rb_define_class(), and rb_define_method().