Ruby: ext/digest/rmd160/rmd160init.c File Reference
rmd160init.c File Reference
#include <ruby/ruby.h>
#include "../digest.h"
#include "rmd160.h"
Macros
#define RUBY_UNTYPED_DATA_WARNING 0
Functions
void Init_rmd160 (void)
Macro Definition Documentation
RUBY_UNTYPED_DATA_WARNING
#define RUBY_UNTYPED_DATA_WARNING 0
Function Documentation
Init_rmd160()
void Init_rmd160 (void)
Definition at line 48 of file rmd160init.c.
References Data_Wrap_Struct, rb_define_class_under(), rb_define_module(), rb_iv_set(), rb_path2class(), and rb_require().