Ruby: ext/openssl/ossl_asn1.h File Reference
ossl_asn1.h File Reference
Functions
VALUE asn1time_to_time (const ASN1_TIME *)
void ossl_time_split (VALUE, time_t *, int *)
VALUE asn1str_to_str (const ASN1_STRING *)
VALUE asn1integer_to_num (const ASN1_INTEGER *)
ASN1_INTEGER * num_to_asn1integer (VALUE, ASN1_INTEGER *)
ASN1_TYPE * ossl_asn1_get_asn1type (VALUE)
void Init_ossl_asn1 (void)
Variables
VALUE mASN1
VALUE eASN1Error
VALUE cASN1Data
VALUE cASN1Primitive
VALUE cASN1Constructive
VALUE cASN1Boolean
VALUE cASN1Integer
VALUE cASN1Enumerated
VALUE cASN1BitString
VALUE cASN1OctetString
VALUE cASN1UTF8String
VALUE cASN1NumericString
VALUE cASN1PrintableString
VALUE cASN1T61String
VALUE cASN1VideotexString
VALUE cASN1IA5String
VALUE cASN1GraphicString
VALUE cASN1ISO64String
VALUE cASN1GeneralString
VALUE cASN1UniversalString
VALUE cASN1BMPString
VALUE cASN1Null
VALUE cASN1ObjectId
VALUE cASN1UTCTime
VALUE cASN1GeneralizedTime
VALUE cASN1Sequence
VALUE cASN1Set
Function Documentation
asn1integer_to_num()
VALUE asn1integer_to_num (const ASN1_INTEGER *)
Definition at line 101 of file ossl_asn1.c.
References eOSSLError, NULL, ossl_bn_new(), ossl_raise(), and rb_eTypeError.
asn1str_to_str()
VALUE asn1str_to_str (const ASN1_STRING *)
Definition at line 92 of file ossl_asn1.c.
References rb_str_new().
asn1time_to_time()
VALUE asn1time_to_time (const ASN1_TIME *)
Definition at line 20 of file ossl_asn1.c.
References argv, count, INT2NUM, ossl_raise(), Qnil, rb_cTime, rb_eTypeError, rb_funcall2, rb_intern, and rb_warning().
Init_ossl_asn1()
void Init_ossl_asn1 (void)
Definition at line 1361 of file ossl_asn1.c.
References eOSSLError, mOSSL, rb_define_class_under(), rb_define_module(), and rb_eStandardError.
num_to_asn1integer()
ASN1_INTEGER* num_to_asn1integer (VALUE , ASN1_INTEGER *)
Definition at line 124 of file ossl_asn1.c.
References eOSSLError, GetBNPtr, NIL_P, NULL, ossl_raise(), and rb_eTypeError.
ossl_asn1_get_asn1type()
ASN1_TYPE* ossl_asn1_get_asn1type (VALUE)
Definition at line 495 of file ossl_asn1.c.
ossl_time_split()
void ossl_time_split (VALUE , time_t * , int *)
Definition at line 73 of file ossl_asn1.c.
References FIX2LONG, FIXNUM_P, INT2FIX, NUM2INT, rb_funcall(), rb_Integer(), rb_intern, and rb_long2int.
Referenced by ossl_x509_time_adjust().
Variable Documentation
cASN1BitString
VALUE cASN1BitString
Definition at line 165 of file ossl_asn1.c.
cASN1BMPString
VALUE cASN1BMPString
Definition at line 171 of file ossl_asn1.c.
cASN1Boolean
VALUE cASN1Boolean
Definition at line 163 of file ossl_asn1.c.
cASN1Constructive
VALUE cASN1Constructive
Definition at line 160 of file ossl_asn1.c.
cASN1Data
VALUE cASN1Data
Definition at line 158 of file ossl_asn1.c.
cASN1Enumerated
VALUE cASN1Enumerated
Definition at line 164 of file ossl_asn1.c.
cASN1GeneralizedTime
VALUE cASN1GeneralizedTime
Definition at line 174 of file ossl_asn1.c.
cASN1GeneralString
VALUE cASN1GeneralString
Definition at line 170 of file ossl_asn1.c.
cASN1GraphicString
VALUE cASN1GraphicString
Definition at line 169 of file ossl_asn1.c.
cASN1IA5String
VALUE cASN1IA5String
Definition at line 169 of file ossl_asn1.c.
cASN1Integer
VALUE cASN1Integer
Definition at line 164 of file ossl_asn1.c.
cASN1ISO64String
VALUE cASN1ISO64String
Definition at line 170 of file ossl_asn1.c.
cASN1Null
VALUE cASN1Null
Definition at line 172 of file ossl_asn1.c.
cASN1NumericString
VALUE cASN1NumericString
Definition at line 167 of file ossl_asn1.c.
cASN1ObjectId
VALUE cASN1ObjectId
Definition at line 173 of file ossl_asn1.c.
cASN1OctetString
VALUE cASN1OctetString
Definition at line 166 of file ossl_asn1.c.
cASN1Primitive
VALUE cASN1Primitive
Definition at line 159 of file ossl_asn1.c.
cASN1PrintableString
VALUE cASN1PrintableString
Definition at line 167 of file ossl_asn1.c.
cASN1Sequence
VALUE cASN1Sequence
Definition at line 175 of file ossl_asn1.c.
cASN1Set
VALUE cASN1Set
Definition at line 175 of file ossl_asn1.c.
cASN1T61String
VALUE cASN1T61String
Definition at line 168 of file ossl_asn1.c.
cASN1UniversalString
VALUE cASN1UniversalString
Definition at line 171 of file ossl_asn1.c.
cASN1UTCTime
VALUE cASN1UTCTime
Definition at line 174 of file ossl_asn1.c.
cASN1UTF8String
VALUE cASN1UTF8String
Definition at line 166 of file ossl_asn1.c.
cASN1VideotexString
VALUE cASN1VideotexString
Definition at line 168 of file ossl_asn1.c.
eASN1Error
VALUE eASN1Error
Definition at line 156 of file ossl_asn1.c.
mASN1
VALUE mASN1
Definition at line 155 of file ossl_asn1.c.