Ruby: ext/openssl/ossl_hmac.c File Reference
ossl_hmac.c File Reference
#include "ossl.h"
Macros
#define NewHMAC(klass) TypedData_Wrap_Struct((klass), &ossl_hmac_type, 0)
#define GetHMAC(obj, ctx)
Functions
void Init_ossl_hmac (void)
Variables
VALUE cHMAC
VALUE eHMACError
Macro Definition Documentation
GetHMAC
#define GetHMAC (obj, ctx)
Value:
do { \
    TypedData_Get_Struct((obj), HMAC_CTX, &ossl_hmac_type, (ctx)); \
    if (!(ctx)) { \
        ossl_raise(rb_eRuntimeError, "HMAC wasn't initialized"); \
    } \
} while (0)
Definition at line 16 of file ossl_hmac.c.
NewHMAC
#define NewHMAC (klass) TypedData_Wrap_Struct((klass), &ossl_hmac_type, 0)
Definition at line 14 of file ossl_hmac.c.
Function Documentation
Init_ossl_hmac()
void Init_ossl_hmac (void)
Definition at line 333 of file ossl_hmac.c.
References cHMAC, eHMACError, eOSSLError, mOSSL, rb_cObject, rb_define_alloc_func(), rb_define_class_under(), rb_define_module(), and rb_eStandardError.
Variable Documentation
cHMAC
VALUE cHMAC
Definition at line 26 of file ossl_hmac.c.
Referenced by Init_ossl_hmac().
eHMACError
VALUE eHMACError
Definition at line 27 of file ossl_hmac.c.
Referenced by Init_ossl_hmac().