Ruby: eval_error.c File Reference
eval_error.c File Reference
Macros
#define warn_print(x) rb_write_error(x)
#define warn_print2(x, l) rb_write_error2((x),(l))
#define warn_print_str(x) rb_write_error_str(x)
#define TRACE_MAX (TRACE_HEAD+TRACE_TAIL+5)
#define TRACE_HEAD 8
#define TRACE_TAIL 5
#define undef_mesg_for(v, k) rb_fstring_cstr("undefined"v" method `%1$s' for "k" `%2$s'")
#define undef_mesg(v)
#define inaccessible_mesg_for(v, k) rb_fstring_cstr("method `%1$s' for "k" `%2$s' is "v)
#define inaccessible_mesg(v)
#define unknown_longjmp_status(status) rb_bug("Unknown longjmp status %d", status)
Functions
void rb_threadptr_error_print (rb_thread_t *volatile th, volatile VALUE errinfo)
void rb_print_undef (VALUE klass, ID id, rb_method_visibility_t visi)
void rb_print_undef_str (VALUE klass, VALUE name)
void rb_print_inaccessible (VALUE klass, ID id, rb_method_visibility_t visi)
Macro Definition Documentation
inaccessible_mesg
#define inaccessible_mesg (v)
Value:
(\
        is_mod ? \
        inaccessible_mesg_for(v, "module") : \
        inaccessible_mesg_for(v, "class"))
Definition at line 238 of file eval_error.c.
Referenced by rb_print_inaccessible().
inaccessible_mesg_for
#define inaccessible_mesg_for (v, k) rb_fstring_cstr("method `%1$s' for "k" `%2$s' is "v)
Definition at line 237 of file eval_error.c.
TRACE_HEAD
#define TRACE_HEAD 8
TRACE_MAX
#define TRACE_MAX (TRACE_HEAD+TRACE_TAIL+5)
TRACE_TAIL
#define TRACE_TAIL 5
undef_mesg
#define undef_mesg (v)
Value:
(\
        is_mod ? \
        undef_mesg_for(v, "module") : \
        undef_mesg_for(v, "class"))
Definition at line 210 of file eval_error.c.
Referenced by rb_print_undef(), and rb_print_undef_str().
undef_mesg_for
#define undef_mesg_for (v, k) rb_fstring_cstr("undefined"v" method `%1$s' for "k" `%2$s'")
Definition at line 209 of file eval_error.c.
unknown_longjmp_status
#define unknown_longjmp_status (status) rb_bug("Unknown longjmp status %d", status)
Definition at line 265 of file eval_error.c.
Referenced by rb_jump_tag().
warn_print
#define warn_print (x) rb_write_error(x)
Definition at line 13 of file eval_error.c.
Referenced by rb_threadptr_error_print().
warn_print2
#define warn_print2 (x, l) rb_write_error2((x),(l))
Definition at line 15 of file eval_error.c.
warn_print_str
#define warn_print_str (x) rb_write_error_str(x)
Definition at line 16 of file eval_error.c.
Function Documentation
rb_print_inaccessible()
void rb_print_inaccessible (VALUE klass, ID id, rb_method_visibility_t visi)
Definition at line 244 of file eval_error.c.
References ID2SYM, inaccessible_mesg, METHOD_VISI_MASK, METHOD_VISI_PRIVATE, METHOD_VISI_PROTECTED, METHOD_VISI_PUBLIC, METHOD_VISI_UNDEF, rb_name_err_raise_str, RB_TYPE_P, T_MODULE, and UNREACHABLE.
rb_print_undef()
void rb_print_undef (VALUE klass, ID id, rb_method_visibility_t visi)
Definition at line 216 of file eval_error.c.
References ID2SYM, METHOD_VISI_MASK, METHOD_VISI_PRIVATE, METHOD_VISI_PROTECTED, METHOD_VISI_PUBLIC, METHOD_VISI_UNDEF, rb_name_err_raise_str, RB_TYPE_P, T_MODULE, undef_mesg, and UNREACHABLE.
rb_print_undef_str()
void rb_print_undef_str (VALUE klass, VALUE name)
Definition at line 231 of file eval_error.c.
References rb_name_err_raise_str, RB_TYPE_P, T_MODULE, and undef_mesg.
rb_threadptr_error_print()
void rb_threadptr_error_print (rb_thread_t *volatile th, volatile VALUE errinfo)
Definition at line 167 of file eval_error.c.
References CLASS_OF, rb_thread_struct::ec, NIL_P, Qnil, Qundef, rb_execution_context_struct::raised_flag, rb_check_funcall(), rb_check_string_type(), rb_get_backtrace(), rb_intern, rb_stderr_tty_p(), rb_thread_raised_clear, RB_TYPE_P, T_STRING, TAG_NONE, TH_EXEC_TAG, TH_PUSH_TAG, and warn_print.
Referenced by rb_f_abort().