Ruby: vm_core.h File Reference
vm_core.h File Reference
#include "ruby_assert.h"
#include "ruby/ruby.h"
#include "ruby/st.h"
#include "node.h"
#include "vm_debug.h"
#include "vm_opts.h"
#include "id.h"
#include "method.h"
#include "ruby_atomic.h"
#include "ccan/list/list.h"
#include "ruby/thread_native.h"
#include <setjmp.h>
#include <signal.h>
#include <varargs.h>
Data Structures
struct iseq_inline_cache_entry
union iseq_inline_storage_entry
struct rb_call_info
struct rb_call_info_kw_arg
struct rb_call_info_with_kwarg
struct rb_calling_info
struct rb_call_cache
struct rb_iseq_location_struct
struct rb_iseq_constant_body
struct rb_iseq_struct
struct rb_at_exit_list
struct rb_hook_list_struct
struct rb_vm_struct
struct rb_captured_block
struct rb_block
struct rb_control_frame_struct
struct rb_vm_tag
struct rb_vm_protect_tag
struct rb_unblock_callback
struct rb_thread_list_struct
struct rb_ensure_entry
struct rb_ensure_list
struct rb_execution_context_struct
struct rb_thread_struct
struct rb_proc_t
struct rb_env_t
struct rb_binding_t
struct rb_trace_arg_struct
Macros
#define VM_CHECK_MODE 0
#define VMDEBUG 0
VM Debug Level.
#define VM_ASSERT(expr) ((void)0)
#define VM_UNREACHABLE(func) UNREACHABLE
#define RUBY_VM_THREAD_MODEL 2
#define ENABLE_VM_OBJSPACE 1
#define NSIG (_SIGMAX + 1) /* For QNX */
#define RUBY_NSIG NSIG
#define va_init_list(a, b) va_start((a))
#define TAG_NONE RUBY_TAG_NONE
#define TAG_RETURN RUBY_TAG_RETURN
#define TAG_BREAK RUBY_TAG_BREAK
#define TAG_NEXT RUBY_TAG_NEXT
#define TAG_RETRY RUBY_TAG_RETRY
#define TAG_REDO RUBY_TAG_REDO
#define TAG_RAISE RUBY_TAG_RAISE
#define TAG_THROW RUBY_TAG_THROW
#define TAG_FATAL RUBY_TAG_FATAL
#define TAG_MASK RUBY_TAG_MASK
#define CoreDataFromValue(obj, type) (type*)DATA_PTR(obj)
#define GetCoreDataFromValue(obj, type, ptr) ((ptr) = CoreDataFromValue((obj), type))
#define PATHOBJ_PATH 0
#define PATHOBJ_REALPATH 1
#define USE_LAZY_LOAD 0
#define GetVMPtr(obj, ptr) GetCoreDataFromValue((obj), rb_vm_t, (ptr))
#define RUBY_VM_SIZE_ALIGN 4096
#define RUBY_VM_THREAD_VM_STACK_SIZE (128 * 1024 * sizeof(VALUE)) /* 512 KB or 1024 KB */
#define RUBY_VM_THREAD_VM_STACK_SIZE_MIN (2 * 1024 * sizeof(VALUE)) /* 8 KB or 16 KB */
#define RUBY_VM_THREAD_MACHINE_STACK_SIZE (128 * 1024 * sizeof(VALUE)) /* 512 KB or 1024 KB */
#define RUBY_VM_THREAD_MACHINE_STACK_SIZE_MIN (16 * 1024 * sizeof(VALUE)) /* 64 KB or 128 KB */
#define RUBY_VM_FIBER_VM_STACK_SIZE (16 * 1024 * sizeof(VALUE)) /* 64 KB or 128 KB */
#define RUBY_VM_FIBER_VM_STACK_SIZE_MIN (2 * 1024 * sizeof(VALUE)) /* 8 KB or 16 KB */
#define RUBY_VM_FIBER_MACHINE_STACK_SIZE (64 * 1024 * sizeof(VALUE)) /* 256 KB or 512 KB */
#define RUBY_VM_FIBER_MACHINE_STACK_SIZE_MIN (16 * 1024 * sizeof(VALUE)) /* 64 KB or 128 KB */
#define INTEGER_REDEFINED_OP_FLAG (1 << 0)
#define FLOAT_REDEFINED_OP_FLAG (1 << 1)
#define STRING_REDEFINED_OP_FLAG (1 << 2)
#define ARRAY_REDEFINED_OP_FLAG (1 << 3)
#define HASH_REDEFINED_OP_FLAG (1 << 4)
#define SYMBOL_REDEFINED_OP_FLAG (1 << 6)
#define TIME_REDEFINED_OP_FLAG (1 << 7)
#define REGEXP_REDEFINED_OP_FLAG (1 << 8)
#define NIL_REDEFINED_OP_FLAG (1 << 9)
#define TRUE_REDEFINED_OP_FLAG (1 << 10)
#define FALSE_REDEFINED_OP_FLAG (1 << 11)
#define BASIC_OP_UNREDEFINED_P(op, klass) (LIKELY((GET_VM()->redefined_flag[(op)]&(klass)) == 0))
#define VM_DEBUG_BP_CHECK 0
#define VM_DEBUG_VERIFY_METHOD_CACHE (VM_DEBUG_MODE != 0)
#define VM_DEFINECLASS_TYPE(x) ((rb_vm_defineclass_type_t)(x) & VM_DEFINECLASS_TYPE_MASK)
#define VM_DEFINECLASS_FLAG_SCOPED 0x08
#define VM_DEFINECLASS_FLAG_HAS_SUPERCLASS 0x10
#define VM_DEFINECLASS_SCOPED_P(x) ((x) & VM_DEFINECLASS_FLAG_SCOPED)
#define VM_DEFINECLASS_HAS_SUPERCLASS_P(x) ((x) & VM_DEFINECLASS_FLAG_HAS_SUPERCLASS)
#define GetProcPtr(obj, ptr) GetCoreDataFromValue((obj), rb_proc_t, (ptr))
#define GetBindingPtr(obj, ptr) GetCoreDataFromValue((obj), rb_binding_t, (ptr))
#define VM_CHECKMATCH_TYPE_MASK 0x03
#define VM_CHECKMATCH_ARRAY 0x04
#define VM_CALL_ARGS_SPLAT (0x01 << VM_CALL_ARGS_SPLAT_bit)
#define VM_CALL_ARGS_BLOCKARG (0x01 << VM_CALL_ARGS_BLOCKARG_bit)
#define VM_CALL_FCALL (0x01 << VM_CALL_FCALL_bit)
#define VM_CALL_VCALL (0x01 << VM_CALL_VCALL_bit)
#define VM_CALL_ARGS_SIMPLE (0x01 << VM_CALL_ARGS_SIMPLE_bit)
#define VM_CALL_BLOCKISEQ (0x01 << VM_CALL_BLOCKISEQ_bit)
#define VM_CALL_KWARG (0x01 << VM_CALL_KWARG_bit)
#define VM_CALL_KW_SPLAT (0x01 << VM_CALL_KW_SPLAT_bit)
#define VM_CALL_TAILCALL (0x01 << VM_CALL_TAILCALL_bit)
#define VM_CALL_SUPER (0x01 << VM_CALL_SUPER_bit)
#define VM_CALL_OPT_SEND (0x01 << VM_CALL_OPT_SEND_bit)
#define FUNC_FASTCALL(x) x
#define VM_TAGGED_PTR_SET(p, tag) ((VALUE)(p) | (tag))
#define VM_TAGGED_PTR_REF(v, mask) ((void *)((v) & ~mask))
#define GC_GUARDED_PTR(p) VM_TAGGED_PTR_SET((p), 0x01)
#define GC_GUARDED_PTR_REF(p) VM_TAGGED_PTR_REF((p), 0x03)
#define GC_GUARDED_PTR_P(p) (((VALUE)(p)) & 0x01)
#define VM_ENV_DATA_SIZE (3)
#define VM_ENV_DATA_INDEX_ME_CREF (-2) /* ep[-2] */
#define VM_ENV_DATA_INDEX_SPECVAL (-1) /* ep[-1] */
#define VM_ENV_DATA_INDEX_FLAGS (0) /* ep[ 0] */
#define VM_ENV_DATA_INDEX_ENV (1) /* ep[ 1] */
#define VM_ENV_DATA_INDEX_ENV_PROC (2) /* ep[ 2] */
#define VM_ENV_INDEX_LAST_LVAR (-VM_ENV_DATA_SIZE)
#define RUBYVM_CFUNC_FRAME_P(cfp) (VM_FRAME_TYPE(cfp) == VM_FRAME_MAGIC_CFUNC)
#define VM_GUARDED_PREV_EP(ep) GC_GUARDED_PTR(ep)
#define VM_BLOCK_HANDLER_NONE 0
#define RUBY_VM_PREVIOUS_CONTROL_FRAME(cfp) ((cfp)+1)
#define RUBY_VM_NEXT_CONTROL_FRAME(cfp) ((cfp)-1)
#define RUBY_VM_END_CONTROL_FRAME(th) ((rb_control_frame_t *)((th)->ec.vm_stack + (th)->ec.vm_stack_size))
#define RUBY_VM_VALID_CONTROL_FRAME_P(cfp, ecfp) ((void *)(ecfp) > (void *)(cfp))
#define RUBY_VM_CONTROL_FRAME_STACK_OVERFLOW_P(th, cfp) (!RUBY_VM_VALID_CONTROL_FRAME_P((cfp), RUBY_VM_END_CONTROL_FRAME(th)))
#define SDR() rb_vmdebug_stack_dump_raw(GET_THREAD(), GET_THREAD()->ec.cfp)
#define SDR2(cfp) rb_vmdebug_stack_dump_raw(GET_THREAD(), (cfp))
#define rb_vm_register_special_exception(sp, e, m) rb_vm_register_special_exception_str(sp, e, rb_usascii_str_new_static((m), (long)rb_strlen_lit(m)))
#define sysstack_error GET_VM()->special_exceptions[ruby_error_sysstack]
#define RUBY_CONST_ASSERT(expr) (1/!!(expr)) /* expr must be a compile-time constant */
#define VM_STACK_OVERFLOWED_P(cfp, sp, margin)
#define WHEN_VM_STACK_OVERFLOWED(cfp, sp, margin) if (LIKELY(!VM_STACK_OVERFLOWED_P(cfp, sp, margin))) {(void)0;} else /* overflowed */
#define CHECK_VM_STACK_OVERFLOW0(cfp, sp, margin) WHEN_VM_STACK_OVERFLOWED(cfp, sp, margin) vm_stackoverflow()
#define CHECK_VM_STACK_OVERFLOW(cfp, margin) WHEN_VM_STACK_OVERFLOWED(cfp, (cfp)->sp, margin) vm_stackoverflow()
#define GET_VM() ruby_current_vm
#define GET_THREAD() ruby_current_thread
#define rb_thread_set_current_raw(th) (void)(ruby_current_thread = (th))
#define rb_thread_set_current(th)
#define RUBY_VM_SET_TIMER_INTERRUPT(th) ATOMIC_OR((th)->interrupt_flag, TIMER_INTERRUPT_MASK)
#define RUBY_VM_SET_INTERRUPT(th) ATOMIC_OR((th)->interrupt_flag, PENDING_INTERRUPT_MASK)
#define RUBY_VM_SET_POSTPONED_JOB_INTERRUPT(th) ATOMIC_OR((th)->interrupt_flag, POSTPONED_JOB_INTERRUPT_MASK)
#define RUBY_VM_SET_TRAP_INTERRUPT(th) ATOMIC_OR((th)->interrupt_flag, TRAP_INTERRUPT_MASK)
#define RUBY_VM_INTERRUPTED(th) ((th)->interrupt_flag & ~(th)->interrupt_mask & (PENDING_INTERRUPT_MASK|TRAP_INTERRUPT_MASK))
#define RUBY_VM_INTERRUPTED_ANY(th) ((th)->interrupt_flag & ~(th)->interrupt_mask)
#define RUBY_VM_CHECK_INTS(th) ruby_vm_check_ints(th)
#define EXEC_EVENT_HOOK_ORIG(th_, flag_, self_, id_, called_id_, klass_, data_, pop_p_)
#define EXEC_EVENT_HOOK(th_, flag_, self_, id_, called_id_, klass_, data_) EXEC_EVENT_HOOK_ORIG(th_, flag_, self_, id_, called_id_, klass_, data_, 0)
#define EXEC_EVENT_HOOK_AND_POP_FRAME(th_, flag_, self_, id_, called_id_, klass_, data_) EXEC_EVENT_HOOK_ORIG(th_, flag_, self_, id_, called_id_, klass_, data_, 1)
Typedefs
typedef unsigned long rb_num_t
typedef struct rb_compile_option_struct rb_compile_option_t
typedef VALUE(* vm_call_handler) (struct rb_thread_struct *th, struct rb_control_frame_struct *cfp, struct rb_calling_info *calling, const struct rb_call_info *ci, struct rb_call_cache *cc)
typedef struct rb_iseq_location_struct rb_iseq_location_t
typedef void rb_vm_at_exit_func(struct rb_vm_struct *)
typedef struct rb_at_exit_list rb_at_exit_list
typedef struct rb_hook_list_struct rb_hook_list_t
typedef struct rb_vm_struct rb_vm_t
typedef struct rb_control_frame_struct rb_control_frame_t
typedef RUBY_JMP_BUF rb_jmpbuf_t
typedef struct rb_thread_list_struct rb_thread_list_t
typedef struct rb_ensure_entry rb_ensure_entry_t
typedef struct rb_ensure_list rb_ensure_list_t
typedef char rb_thread_id_string_t[sizeof(rb_nativethread_id_t) *2+3]
typedef struct rb_fiber_struct rb_fiber_t
typedef struct rb_execution_context_struct rb_execution_context_t
typedef struct rb_thread_struct rb_thread_t
typedef struct iseq_inline_cache_entry * IC
typedef struct rb_call_info * CALL_INFO
typedef struct rb_call_cache * CALL_CACHE
typedef VALUE CDHASH
typedef rb_control_frame_t *FUNC_FASTCALL rb_insn_func_t(rb_thread_t *, rb_control_frame_t *)
typedef int rb_backtrace_iter_func(void *, VALUE, int, VALUE)
Enumerations
enum ruby_tag_type {
RUBY_TAG_NONE = 0x0, RUBY_TAG_RETURN = 0x1, RUBY_TAG_BREAK = 0x2, RUBY_TAG_NEXT = 0x3,
RUBY_TAG_RETRY = 0x4, RUBY_TAG_REDO = 0x5, RUBY_TAG_RAISE = 0x6, RUBY_TAG_THROW = 0x7,
RUBY_TAG_FATAL = 0x8, RUBY_TAG_MASK = 0xf
}
enum ruby_vm_throw_flags { VM_THROW_NO_ESCAPE_FLAG = 0x8000, VM_THROW_LEVEL_SHIFT = 16, VM_THROW_STATE_MASK = 0xff }
enum method_missing_reason {
MISSING_NOENTRY = 0x00, MISSING_PRIVATE = 0x01, MISSING_PROTECTED = 0x02, MISSING_FCALL = 0x04,
MISSING_VCALL = 0x08, MISSING_SUPER = 0x10, MISSING_MISSING = 0x20, MISSING_NONE = 0x40
}
enum ruby_special_exceptions {
ruby_error_reenter, ruby_error_nomemory, ruby_error_sysstack, ruby_error_stackfatal,
ruby_error_stream_closed, ruby_special_error_count
}
enum ruby_basic_operators {
BOP_PLUS, BOP_MINUS, BOP_MULT, BOP_DIV,
BOP_MOD, BOP_EQ, BOP_EQQ, BOP_LT,
BOP_LE, BOP_LTLT, BOP_AREF, BOP_ASET,
BOP_LENGTH, BOP_SIZE, BOP_EMPTY_P, BOP_SUCC,
BOP_GT, BOP_GE, BOP_NOT, BOP_NEQ,
BOP_MATCH, BOP_FREEZE, BOP_UMINUS, BOP_MAX,
BOP_MIN, BOP_LAST_
}
enum rb_block_handler_type { block_handler_type_iseq, block_handler_type_ifunc, block_handler_type_symbol, block_handler_type_proc }
enum rb_block_type { block_type_iseq, block_type_ifunc, block_type_symbol, block_type_proc }
enum rb_thread_status { THREAD_RUNNABLE, THREAD_STOPPED, THREAD_STOPPED_FOREVER, THREAD_KILLED }
enum rb_vm_defineclass_type_t { VM_DEFINECLASS_TYPE_CLASS = 0x00, VM_DEFINECLASS_TYPE_SINGLETON_CLASS = 0x01, VM_DEFINECLASS_TYPE_MODULE = 0x02, VM_DEFINECLASS_TYPE_MASK = 0x07 }
enum vm_check_match_type { VM_CHECKMATCH_TYPE_WHEN = 1, VM_CHECKMATCH_TYPE_CASE = 2, VM_CHECKMATCH_TYPE_RESCUE = 3 }
enum vm_call_flag_bits {
VM_CALL_ARGS_SPLAT_bit, VM_CALL_ARGS_BLOCKARG_bit, VM_CALL_FCALL_bit, VM_CALL_VCALL_bit,
VM_CALL_ARGS_SIMPLE_bit, VM_CALL_BLOCKISEQ_bit, VM_CALL_KWARG_bit, VM_CALL_KW_SPLAT_bit,
VM_CALL_TAILCALL_bit, VM_CALL_SUPER_bit, VM_CALL_OPT_SEND_bit, VM_CALL__END
}
enum vm_special_object_type { VM_SPECIAL_OBJECT_VMCORE = 1, VM_SPECIAL_OBJECT_CBASE, VM_SPECIAL_OBJECT_CONST_BASE }
enum vm_svar_index { VM_SVAR_LASTLINE = 0, VM_SVAR_BACKREF = 1, VM_SVAR_EXTRA_START = 2, VM_SVAR_FLIPFLOP_START = 2 }
enum {
VM_FRAME_MAGIC_METHOD = 0x11110001, VM_FRAME_MAGIC_BLOCK = 0x22220001, VM_FRAME_MAGIC_CLASS = 0x33330001, VM_FRAME_MAGIC_TOP = 0x44440001,
VM_FRAME_MAGIC_CFUNC = 0x55550001, VM_FRAME_MAGIC_IFUNC = 0x66660001, VM_FRAME_MAGIC_EVAL = 0x77770001, VM_FRAME_MAGIC_RESCUE = 0x88880001,
VM_FRAME_MAGIC_DUMMY = 0x99990001, VM_FRAME_MAGIC_MASK = 0xffff0001, VM_FRAME_FLAG_PASSED = 0x0010, VM_FRAME_FLAG_FINISH = 0x0020,
VM_FRAME_FLAG_BMETHOD = 0x0040, VM_FRAME_FLAG_CFRAME = 0x0080, VM_FRAME_FLAG_LAMBDA = 0x0100, VM_ENV_FLAG_LOCAL = 0x0002,
VM_ENV_FLAG_ESCAPED = 0x0004, VM_ENV_FLAG_WB_REQUIRED = 0x0008
}
enum { TIMER_INTERRUPT_MASK = 0x01, PENDING_INTERRUPT_MASK = 0x02, POSTPONED_JOB_INTERRUPT_MASK = 0x04, TRAP_INTERRUPT_MASK = 0x08 }
Functions
struct rb_objspace * rb_objspace_alloc (void)
void rb_objspace_free (struct rb_objspace *)
STATIC_ASSERT (rb_vm_tag_buf_offset, offsetof(struct rb_vm_tag, buf) > 0)
STATIC_ASSERT (rb_vm_tag_buf_end, offsetof(struct rb_vm_tag, buf)+sizeof(rb_jmpbuf_t)< sizeof(struct rb_vm_tag))
RUBY_SYMBOL_EXPORT_BEGIN rb_iseq_t * rb_iseq_new (NODE *node, VALUE name, VALUE path, VALUE realpath, const rb_iseq_t *parent, enum iseq_type)
rb_iseq_t * rb_iseq_new_top (NODE *node, VALUE name, VALUE path, VALUE realpath, const rb_iseq_t *parent)
rb_iseq_t * rb_iseq_new_main (NODE *node, VALUE path, VALUE realpath, const rb_iseq_t *parent)
rb_iseq_t * rb_iseq_new_with_opt (NODE *node, VALUE name, VALUE path, VALUE realpath, VALUE first_lineno, const rb_iseq_t *parent, enum iseq_type, const rb_compile_option_t *)
rb_iseq_t * rb_iseq_compile (VALUE src, VALUE file, VALUE line)
rb_iseq_t * rb_iseq_compile_on_base (VALUE src, VALUE file, VALUE line, const struct rb_block *base_block)
rb_iseq_t * rb_iseq_compile_with_option (VALUE src, VALUE file, VALUE realpath, VALUE line, const struct rb_block *base_block, VALUE opt)
VALUE rb_iseq_disasm (const rb_iseq_t *iseq)
int rb_iseq_disasm_insn (VALUE str, const VALUE *iseqval, size_t pos, const rb_iseq_t *iseq, VALUE child)
Disassemble a instruction Iseq -> Iseq inspect object.
const char * ruby_node_name (int node)
VALUE rb_iseq_coverage (const rb_iseq_t *iseq)
void rb_vm_change_state (void)
const VALUE * rb_vm_ep_local_ep (const VALUE *ep)
const VALUE * rb_vm_proc_local_ep (VALUE proc)
void rb_vm_block_ep_update (VALUE obj, const struct rb_block *dst, const VALUE *ep)
void rb_vm_block_copy (VALUE obj, const struct rb_block *dst, const struct rb_block *src)
VALUE rb_vm_frame_block_handler (const rb_control_frame_t *cfp)
VALUE rb_thread_alloc (VALUE klass)
VALUE rb_proc_alloc (VALUE klass)
VALUE rb_binding_alloc (VALUE klass)
void rb_vmdebug_stack_dump_raw (rb_thread_t *, rb_control_frame_t *)
void rb_vmdebug_debug_print_pre (rb_thread_t *th, rb_control_frame_t *cfp, const VALUE *_pc)
void rb_vmdebug_debug_print_post (rb_thread_t *th, rb_control_frame_t *cfp)
void rb_vm_bugreport (const void *)
NORETURN (void rb_bug_context(const void *, const char *fmt,...))
RUBY_SYMBOL_EXPORT_BEGIN VALUE rb_iseq_eval (const rb_iseq_t *iseq)
VALUE rb_iseq_eval_main (const rb_iseq_t *iseq)
VALUE rb_iseq_path (const rb_iseq_t *iseq)
VALUE rb_iseq_realpath (const rb_iseq_t *iseq)
RUBY_SYMBOL_EXPORT_END VALUE rb_iseq_pathobj_new (VALUE path, VALUE realpath)
void rb_iseq_pathobj_set (const rb_iseq_t *iseq, VALUE path, VALUE realpath)
int rb_thread_method_id_and_class (rb_thread_t *th, ID *idp, ID *called_idp, VALUE *klassp)
VALUE rb_vm_invoke_proc (rb_thread_t *th, rb_proc_t *proc, int argc, const VALUE *argv, VALUE block_handler)
VALUE rb_vm_make_proc_lambda (rb_thread_t *th, const struct rb_captured_block *captured, VALUE klass, int8_t is_lambda)
VALUE rb_vm_make_proc (rb_thread_t *th, const struct rb_captured_block *captured, VALUE klass)
VALUE rb_vm_make_binding (rb_thread_t *th, const rb_control_frame_t *src_cfp)
VALUE rb_vm_env_local_variables (const rb_env_t *env)
const rb_env_t * rb_vm_env_prev_env (const rb_env_t *env)
const VALUE * rb_binding_add_dynavars (VALUE bindval, rb_binding_t *bind, int dyncount, const ID *dynvars)
void rb_vm_inc_const_missing_count (void)
void rb_vm_gvl_destroy (rb_vm_t *vm)
VALUE rb_vm_call (rb_thread_t *th, VALUE recv, VALUE id, int argc, const VALUE *argv, const rb_callable_method_entry_t *me)
void rb_vm_pop_frame (rb_thread_t *th)
void rb_thread_start_timer_thread (void)
void rb_thread_stop_timer_thread (void)
void rb_thread_reset_timer_thread (void)
void rb_thread_wakeup_timer_thread (void)
rb_control_frame_t * rb_vm_get_ruby_level_next_cfp (const rb_thread_t *th, const rb_control_frame_t *cfp)
rb_control_frame_t * rb_vm_get_binding_creatable_next_cfp (const rb_thread_t *th, const rb_control_frame_t *cfp)
int rb_vm_get_sourceline (const rb_control_frame_t *)
VALUE rb_name_err_mesg_new (VALUE mesg, VALUE recv, VALUE method)
void rb_vm_stack_to_heap (rb_thread_t *th)
void ruby_thread_init_stack (rb_thread_t *th)
int rb_vm_control_frame_id_and_class (const rb_control_frame_t *cfp, ID *idp, ID *called_idp, VALUE *klassp)
void rb_vm_rewind_cfp (rb_thread_t *th, rb_control_frame_t *cfp)
void rb_vm_register_special_exception_str (enum ruby_special_exceptions sp, VALUE exception_class, VALUE mesg)
void rb_gc_mark_machine_stack (const rb_execution_context_t *ec)
int rb_autoloading_value (VALUE mod, ID id, VALUE *value)
void rb_vm_rewrite_cref (rb_cref_t *node, VALUE old_klass, VALUE new_klass, rb_cref_t **new_cref_ptr)
const rb_callable_method_entry_t * rb_vm_frame_method_entry (const rb_control_frame_t *cfp)
VALUE rb_catch_protect (VALUE t, rb_block_call_func *func, VALUE data, enum ruby_tag_type *stateptr)
VALUE rb_exc_set_backtrace (VALUE exc, VALUE bt)
int rb_signal_buff_size (void)
void rb_signal_exec (rb_thread_t *th, int sig)
void rb_threadptr_check_signal (rb_thread_t *mth)
void rb_threadptr_signal_raise (rb_thread_t *th, int sig)
void rb_threadptr_signal_exit (rb_thread_t *th)
void rb_threadptr_execute_interrupts (rb_thread_t *, int)
void rb_threadptr_interrupt (rb_thread_t *th)
void rb_threadptr_unlock_all_locking_mutexes (rb_thread_t *th)
void rb_threadptr_pending_interrupt_clear (rb_thread_t *th)
void rb_threadptr_pending_interrupt_enque (rb_thread_t *th, VALUE v)
int rb_threadptr_pending_interrupt_active_p (rb_thread_t *th)
void rb_threadptr_error_print (rb_thread_t *volatile th, volatile VALUE errinfo)
void rb_execution_context_mark (const rb_execution_context_t *ec)
void rb_threadptr_exec_event_hooks (struct rb_trace_arg_struct *trace_arg)
void rb_threadptr_exec_event_hooks_and_pop_frame (struct rb_trace_arg_struct *trace_arg)
RUBY_SYMBOL_EXPORT_BEGIN int rb_thread_check_trap_pending (void)
VALUE rb_get_coverages (void)
void rb_set_coverages (VALUE, int)
void rb_reset_coverages (void)
void rb_postponed_job_flush (rb_vm_t *vm)
Variables
const rb_data_type_t ruby_threadptr_data_type
RUBY_EXTERN VALUE rb_cISeq
RUBY_EXTERN VALUE rb_cRubyVM
RUBY_EXTERN VALUE rb_mRubyVMFrozenCore
const rb_data_type_t ruby_binding_data_type
RUBY_SYMBOL_EXPORT_BEGIN rb_thread_t * ruby_current_thread
rb_vm_t * ruby_current_vm
rb_event_flag_t ruby_vm_event_flags
Macro Definition Documentation
ARRAY_REDEFINED_OP_FLAG
#define ARRAY_REDEFINED_OP_FLAG (1 << 3)
Definition at line 609 of file vm_core.h.
BASIC_OP_UNREDEFINED_P
#define BASIC_OP_UNREDEFINED_P (op, klass) (LIKELY((GET_VM()->redefined_flag[(op)]&(klass)) == 0))
Definition at line 619 of file vm_core.h.
CHECK_VM_STACK_OVERFLOW
#define CHECK_VM_STACK_OVERFLOW (cfp, margin) WHEN_VM_STACK_OVERFLOWED(cfp, (cfp)->sp, margin) vm_stackoverflow()
Definition at line 1565 of file vm_core.h.
CHECK_VM_STACK_OVERFLOW0
#define CHECK_VM_STACK_OVERFLOW0 (cfp, sp, margin) WHEN_VM_STACK_OVERFLOWED(cfp, sp, margin) vm_stackoverflow()
Definition at line 1563 of file vm_core.h.
CoreDataFromValue
#define CoreDataFromValue (obj, type) (type*)DATA_PTR(obj)
Definition at line 260 of file vm_core.h.
ENABLE_VM_OBJSPACE
#define ENABLE_VM_OBJSPACE 1
Definition at line 86 of file vm_core.h.
EXEC_EVENT_HOOK
#define EXEC_EVENT_HOOK (th_, flag_, self_, id_, called_id_, klass_, data_) EXEC_EVENT_HOOK_ORIG(th_, flag_, self_, id_, called_id_, klass_, data_, 0)
Definition at line 1686 of file vm_core.h.
Referenced by rb_fiber_start(), and rb_vm_pop_cfunc_frame().
EXEC_EVENT_HOOK_AND_POP_FRAME
#define EXEC_EVENT_HOOK_AND_POP_FRAME (th_, flag_, self_, id_, called_id_, klass_, data_) EXEC_EVENT_HOOK_ORIG(th_, flag_, self_, id_, called_id_, klass_, data_, 1)
Definition at line 1689 of file vm_core.h.
EXEC_EVENT_HOOK_ORIG
#define EXEC_EVENT_HOOK_ORIG (th_, flag_, self_, id_, called_id_, klass_, data_, pop_p_)
Value:
do { \
    const rb_event_flag_t flag_arg_ = (flag_); \
    if (UNLIKELY(ruby_vm_event_flags & (flag_arg_))) { \
        /* defer evaluating the other arguments */ \
        ruby_exec_event_hook_orig(th_, flag_arg_, self_, id_, called_id_, klass_, data_, pop_p_); \
    } \
} while (0)
Definition at line 1657 of file vm_core.h.
FALSE_REDEFINED_OP_FLAG
#define FALSE_REDEFINED_OP_FLAG (1 << 11)
Definition at line 617 of file vm_core.h.
FLOAT_REDEFINED_OP_FLAG
#define FLOAT_REDEFINED_OP_FLAG (1 << 1)
Definition at line 607 of file vm_core.h.
FUNC_FASTCALL
#define FUNC_FASTCALL (x) x
Definition at line 998 of file vm_core.h.
GC_GUARDED_PTR
#define GC_GUARDED_PTR (p) VM_TAGGED_PTR_SET((p), 0x01)
Definition at line 1007 of file vm_core.h.
GC_GUARDED_PTR_P
#define GC_GUARDED_PTR_P (p) (((VALUE)(p)) & 0x01)
Definition at line 1009 of file vm_core.h.
GC_GUARDED_PTR_REF
#define GC_GUARDED_PTR_REF (p) VM_TAGGED_PTR_REF((p), 0x03)
Definition at line 1008 of file vm_core.h.
Referenced by rb_vmdebug_stack_dump_raw().
GET_THREAD
#define GET_THREAD () ruby_current_thread
Definition at line 1583 of file vm_core.h.
Referenced by Init_Cont(), Init_Thread(), rb_binding_new(), rb_block_given_p(), rb_block_min_max_arity(), rb_bug(), rb_bug_context(), rb_call_super(), rb_catch_obj(), rb_check_funcall_default(), rb_check_funcall_with_hook(), rb_current_realfilepath(), rb_current_receiver(), rb_debug_inspector_open(), rb_errinfo(), rb_eval_cmd(), rb_eval_string_wrap(), rb_exec_end_proc(), rb_exit(), rb_f_abort(), rb_f_block_given_p(), rb_fiber_start(), rb_frame_last_func(), rb_frame_method_id_and_class(), rb_funcall_with_block(), rb_gc_register_mark_object(), rb_iseq_compile_with_option(), rb_iseq_eval(), rb_iseq_eval_main(), rb_last_status_clear(), rb_last_status_get(), rb_last_status_set(), rb_make_backtrace(), rb_memerror(), rb_method_call_with_block(), rb_mutex_lock(), rb_mutex_owned_p(), rb_mutex_trylock(), rb_notify_fd_close(), rb_obj_respond_to(), rb_postponed_job_flush(), rb_postponed_job_register(), rb_postponed_job_register_one(), rb_proc_call(), rb_proc_call_with_block(), rb_proc_create(), rb_proc_create_from_captured(), rb_profile_frames(), rb_require_internal(), rb_rescue2(), rb_safe_level(), rb_set_end_proc(), rb_set_errinfo(), rb_set_safe_level(), rb_set_safe_level_force(), rb_source_location(), rb_sourcefile(), rb_sourcefilename(), rb_sourceline(), rb_thread_check_ints(), rb_thread_current(), rb_thread_io_blocking_region(), rb_thread_list(), rb_thread_main(), rb_thread_schedule(), rb_thread_shield_wait(), rb_thread_terminate_all(), rb_thread_wait_for(), rb_throw_obj(), rb_uninterruptible(), rb_vm_call_cfunc(), rb_vm_cbase(), rb_vm_cref(), rb_vm_cref_in_context(), rb_vm_cref_replace_with_duplicated_cref(), rb_vm_make_jump_tag_but_local_jump(), rb_vm_pop_cfunc_frame(), rb_vmdebug_stack_dump_all_threads(), rb_vmdebug_stack_dump_raw_current(), rb_yield_refine_block(), ruby_cleanup(), ruby_options(), ruby_stack_length(), and ruby_th_dtrace_setup().
GET_VM
#define GET_VM () ruby_current_vm
Definition at line 1582 of file vm_core.h.
Referenced by Init_load(), Init_top_self(), Init_vm_objects(), rb_clear_trace_func(), rb_get_coverages(), rb_get_expanded_load_path(), rb_get_load_path(), rb_iseq_defined_string(), rb_set_coverages(), rb_signal_exec(), rb_thread_io_blocking_region(), rb_trap_exit(), rb_vm_add_root_module(), rb_vm_bugreport(), rb_vm_fstring_table(), rb_vm_register_special_exception_str(), rb_vm_set_progname(), rb_vm_top_self(), ruby_register_rollback_func_for_ensure(), ruby_setup(), and ruby_vm_at_exit().
GetBindingPtr
#define GetBindingPtr (obj, ptr) GetCoreDataFromValue((obj), rb_binding_t, (ptr))
Definition at line 927 of file vm_core.h.
GetCoreDataFromValue
#define GetCoreDataFromValue (obj, type, ptr) ((ptr) = CoreDataFromValue((obj), type))
Definition at line 264 of file vm_core.h.
Referenced by rb_backtrace_to_location_ary(), and rb_backtrace_to_str_ary().
GetProcPtr
#define GetProcPtr (obj, ptr) GetCoreDataFromValue((obj), rb_proc_t, (ptr))
Definition at line 907 of file vm_core.h.
Referenced by rb_fiber_start(), rb_proc_call(), rb_proc_call_with_block(), rb_proc_get_iseq(), and rb_proc_lambda_p().
GetVMPtr
#define GetVMPtr (obj, ptr) GetCoreDataFromValue((obj), rb_vm_t, (ptr))
Definition at line 493 of file vm_core.h.
HASH_REDEFINED_OP_FLAG
#define HASH_REDEFINED_OP_FLAG (1 << 4)
Definition at line 610 of file vm_core.h.
INTEGER_REDEFINED_OP_FLAG
#define INTEGER_REDEFINED_OP_FLAG (1 << 0)
Definition at line 606 of file vm_core.h.
NIL_REDEFINED_OP_FLAG
#define NIL_REDEFINED_OP_FLAG (1 << 9)
Definition at line 615 of file vm_core.h.
NSIG
#define NSIG (_SIGMAX + 1) /* For QNX */
Definition at line 94 of file vm_core.h.
PATHOBJ_PATH
#define PATHOBJ_PATH 0
Definition at line 273 of file vm_core.h.
PATHOBJ_REALPATH
#define PATHOBJ_REALPATH 1
Definition at line 274 of file vm_core.h.
rb_thread_set_current
#define rb_thread_set_current (th)
Value:
do { \
    if ((th)->vm->running_thread != (th)) { \
        (th)->running_time_us = 0; \
    } \
    rb_thread_set_current_raw(th); \
    (th)->vm->running_thread = (th); \
} while (0)
Definition at line 1586 of file vm_core.h.
rb_thread_set_current_raw
#define rb_thread_set_current_raw (th) (void)(ruby_current_thread = (th))
Definition at line 1585 of file vm_core.h.
Referenced by Init_BareVM().
rb_vm_register_special_exception
#define rb_vm_register_special_exception (sp, e, m) rb_vm_register_special_exception_str(sp, e, rb_usascii_str_new_static((m), (long)rb_strlen_lit(m)))
Definition at line 1543 of file vm_core.h.
REGEXP_REDEFINED_OP_FLAG
#define REGEXP_REDEFINED_OP_FLAG (1 << 8)
Definition at line 614 of file vm_core.h.
RUBY_CONST_ASSERT
#define RUBY_CONST_ASSERT (expr) (1/!!(expr)) /* expr must be a compile-time constant */
Definition at line 1556 of file vm_core.h.
RUBY_NSIG
#define RUBY_NSIG NSIG
Definition at line 97 of file vm_core.h.
Referenced by rb_vm_mark().
RUBY_VM_CHECK_INTS
#define RUBY_VM_CHECK_INTS (th) ruby_vm_check_ints(th)
Definition at line 1627 of file vm_core.h.
Referenced by ruby_cleanup().
RUBY_VM_CONTROL_FRAME_STACK_OVERFLOW_P
#define RUBY_VM_CONTROL_FRAME_STACK_OVERFLOW_P (th, cfp) (!RUBY_VM_VALID_CONTROL_FRAME_P((cfp), RUBY_VM_END_CONTROL_FRAME(th)))
Definition at line 1244 of file vm_core.h.
Referenced by rb_vm_get_binding_creatable_next_cfp(), and rb_vm_get_ruby_level_next_cfp().
RUBY_VM_END_CONTROL_FRAME
#define RUBY_VM_END_CONTROL_FRAME (th) ((rb_control_frame_t *)((th)->ec.vm_stack + (th)->ec.vm_stack_size))
Definition at line 1240 of file vm_core.h.
Referenced by rb_profile_frames().
RUBY_VM_FIBER_MACHINE_STACK_SIZE
#define RUBY_VM_FIBER_MACHINE_STACK_SIZE (64 * 1024 * sizeof(VALUE)) /* 256 KB or 512 KB */
Definition at line 602 of file vm_core.h.
RUBY_VM_FIBER_MACHINE_STACK_SIZE_MIN
#define RUBY_VM_FIBER_MACHINE_STACK_SIZE_MIN (16 * 1024 * sizeof(VALUE)) /* 64 KB or 128 KB */
Definition at line 603 of file vm_core.h.
RUBY_VM_FIBER_VM_STACK_SIZE
#define RUBY_VM_FIBER_VM_STACK_SIZE (16 * 1024 * sizeof(VALUE)) /* 64 KB or 128 KB */
Definition at line 600 of file vm_core.h.
RUBY_VM_FIBER_VM_STACK_SIZE_MIN
#define RUBY_VM_FIBER_VM_STACK_SIZE_MIN (2 * 1024 * sizeof(VALUE)) /* 8 KB or 16 KB */
Definition at line 601 of file vm_core.h.
RUBY_VM_INTERRUPTED
#define RUBY_VM_INTERRUPTED (th) ((th)->interrupt_flag & ~(th)->interrupt_mask & (PENDING_INTERRUPT_MASK|TRAP_INTERRUPT_MASK))
Definition at line 1609 of file vm_core.h.
Referenced by rb_thread_interrupted().
RUBY_VM_INTERRUPTED_ANY
#define RUBY_VM_INTERRUPTED_ANY (th) ((th)->interrupt_flag & ~(th)->interrupt_mask)
Definition at line 1610 of file vm_core.h.
RUBY_VM_NEXT_CONTROL_FRAME
#define RUBY_VM_NEXT_CONTROL_FRAME (cfp) ((cfp)-1)
Definition at line 1239 of file vm_core.h.
RUBY_VM_PREVIOUS_CONTROL_FRAME
#define RUBY_VM_PREVIOUS_CONTROL_FRAME (cfp) ((cfp)+1)
Definition at line 1238 of file vm_core.h.
Referenced by rb_vm_get_binding_creatable_next_cfp().
RUBY_VM_SET_INTERRUPT
#define RUBY_VM_SET_INTERRUPT (th) ATOMIC_OR((th)->interrupt_flag, PENDING_INTERRUPT_MASK)
Definition at line 1606 of file vm_core.h.
Referenced by rb_fiber_start().
RUBY_VM_SET_POSTPONED_JOB_INTERRUPT
#define RUBY_VM_SET_POSTPONED_JOB_INTERRUPT (th) ATOMIC_OR((th)->interrupt_flag, POSTPONED_JOB_INTERRUPT_MASK)
Definition at line 1607 of file vm_core.h.
Referenced by rb_postponed_job_register_one().
RUBY_VM_SET_TIMER_INTERRUPT
#define RUBY_VM_SET_TIMER_INTERRUPT (th) ATOMIC_OR((th)->interrupt_flag, TIMER_INTERRUPT_MASK)
Definition at line 1605 of file vm_core.h.
RUBY_VM_SET_TRAP_INTERRUPT
#define RUBY_VM_SET_TRAP_INTERRUPT (th) ATOMIC_OR((th)->interrupt_flag, TRAP_INTERRUPT_MASK)
Definition at line 1608 of file vm_core.h.
RUBY_VM_SIZE_ALIGN
#define RUBY_VM_SIZE_ALIGN 4096
Definition at line 593 of file vm_core.h.
RUBY_VM_THREAD_MACHINE_STACK_SIZE
#define RUBY_VM_THREAD_MACHINE_STACK_SIZE (128 * 1024 * sizeof(VALUE)) /* 512 KB or 1024 KB */
Definition at line 597 of file vm_core.h.
RUBY_VM_THREAD_MACHINE_STACK_SIZE_MIN
#define RUBY_VM_THREAD_MACHINE_STACK_SIZE_MIN (16 * 1024 * sizeof(VALUE)) /* 64 KB or 128 KB */
Definition at line 598 of file vm_core.h.
RUBY_VM_THREAD_MODEL
#define RUBY_VM_THREAD_MODEL 2
Definition at line 57 of file vm_core.h.
RUBY_VM_THREAD_VM_STACK_SIZE
#define RUBY_VM_THREAD_VM_STACK_SIZE (128 * 1024 * sizeof(VALUE)) /* 512 KB or 1024 KB */
Definition at line 595 of file vm_core.h.
RUBY_VM_THREAD_VM_STACK_SIZE_MIN
#define RUBY_VM_THREAD_VM_STACK_SIZE_MIN (2 * 1024 * sizeof(VALUE)) /* 8 KB or 16 KB */
Definition at line 596 of file vm_core.h.
RUBY_VM_VALID_CONTROL_FRAME_P
#define RUBY_VM_VALID_CONTROL_FRAME_P (cfp, ecfp) ((void *)(ecfp) > (void *)(cfp))
Definition at line 1242 of file vm_core.h.
RUBYVM_CFUNC_FRAME_P
#define RUBYVM_CFUNC_FRAME_P (cfp) (VM_FRAME_TYPE(cfp) == VM_FRAME_MAGIC_CFUNC)
Definition at line 1131 of file vm_core.h.
SDR
#define SDR () rb_vmdebug_stack_dump_raw(GET_THREAD(), GET_THREAD()->ec.cfp)
Definition at line 1473 of file vm_core.h.
Referenced by rb_vm_bugreport().
SDR2
#define SDR2 (cfp) rb_vmdebug_stack_dump_raw(GET_THREAD(), (cfp))
Definition at line 1474 of file vm_core.h.
Referenced by rb_vmdebug_debug_print_post().
STRING_REDEFINED_OP_FLAG
#define STRING_REDEFINED_OP_FLAG (1 << 2)
Definition at line 608 of file vm_core.h.
SYMBOL_REDEFINED_OP_FLAG
#define SYMBOL_REDEFINED_OP_FLAG (1 << 6)
Definition at line 612 of file vm_core.h.
sysstack_error
#define sysstack_error GET_VM()->special_exceptions[ruby_error_sysstack]
Definition at line 1554 of file vm_core.h.
TAG_BREAK
#define TAG_BREAK RUBY_TAG_BREAK
Definition at line 166 of file vm_core.h.
Referenced by rb_vm_make_jump_tag_but_local_jump().
TAG_FATAL
#define TAG_FATAL RUBY_TAG_FATAL
Definition at line 172 of file vm_core.h.
Referenced by rb_fiber_start(), and rb_jump_tag().
TAG_MASK
#define TAG_MASK RUBY_TAG_MASK
Definition at line 173 of file vm_core.h.
TAG_NEXT
#define TAG_NEXT RUBY_TAG_NEXT
Definition at line 167 of file vm_core.h.
Referenced by rb_vm_make_jump_tag_but_local_jump().
TAG_NONE
#define TAG_NONE RUBY_TAG_NONE
Definition at line 164 of file vm_core.h.
Referenced by rb_eval_cmd(), rb_eval_string_wrap(), rb_exec_end_proc(), rb_fiber_start(), rb_load_protect(), rb_postponed_job_flush(), rb_require_internal(), rb_thread_io_blocking_region(), rb_thread_terminate_all(), rb_threadptr_error_print(), ruby_cleanup(), ruby_options(), and ruby_setup().
TAG_RAISE
#define TAG_RAISE RUBY_TAG_RAISE
Definition at line 170 of file vm_core.h.
Referenced by rb_fiber_start(), rb_require_safe(), and rb_threadptr_stack_overflow().
TAG_REDO
#define TAG_REDO RUBY_TAG_REDO
Definition at line 169 of file vm_core.h.
Referenced by rb_vm_make_jump_tag_but_local_jump().
TAG_RETRY
#define TAG_RETRY RUBY_TAG_RETRY
Definition at line 168 of file vm_core.h.
Referenced by rb_vm_make_jump_tag_but_local_jump().
TAG_RETURN
#define TAG_RETURN RUBY_TAG_RETURN
Definition at line 165 of file vm_core.h.
Referenced by rb_require_safe(), rb_vm_make_jump_tag_but_local_jump(), and ruby_require_internal().
TAG_THROW
#define TAG_THROW RUBY_TAG_THROW
Definition at line 171 of file vm_core.h.
TIME_REDEFINED_OP_FLAG
#define TIME_REDEFINED_OP_FLAG (1 << 7)
Definition at line 613 of file vm_core.h.
TRUE_REDEFINED_OP_FLAG
#define TRUE_REDEFINED_OP_FLAG (1 << 10)
Definition at line 616 of file vm_core.h.
USE_LAZY_LOAD
#define USE_LAZY_LOAD 0
Definition at line 436 of file vm_core.h.
va_init_list
#define va_init_list (a, b) va_start((a))
Definition at line 104 of file vm_core.h.
VM_ASSERT
#define VM_ASSERT (expr) ((void)0)
Definition at line 53 of file vm_core.h.
Referenced by rb_execution_context_mark(), rb_fiber_start(), rb_iseq_pathobj_new(), rb_proc_create(), rb_proc_create_from_captured(), and rb_thread_recycle_stack_release().
VM_BLOCK_HANDLER_NONE
#define VM_BLOCK_HANDLER_NONE 0
Definition at line 1135 of file vm_core.h.
Referenced by rb_block_given_p(), rb_block_min_max_arity(), rb_fiber_start(), and rb_proc_call().
VM_CALL_ARGS_BLOCKARG
#define VM_CALL_ARGS_BLOCKARG (0x01 << VM_CALL_ARGS_BLOCKARG_bit)
Definition at line 963 of file vm_core.h.
VM_CALL_ARGS_SIMPLE
#define VM_CALL_ARGS_SIMPLE (0x01 << VM_CALL_ARGS_SIMPLE_bit)
Definition at line 966 of file vm_core.h.
VM_CALL_ARGS_SPLAT
#define VM_CALL_ARGS_SPLAT (0x01 << VM_CALL_ARGS_SPLAT_bit)
Definition at line 962 of file vm_core.h.
VM_CALL_BLOCKISEQ
#define VM_CALL_BLOCKISEQ (0x01 << VM_CALL_BLOCKISEQ_bit)
Definition at line 967 of file vm_core.h.
VM_CALL_FCALL
#define VM_CALL_FCALL (0x01 << VM_CALL_FCALL_bit)
Definition at line 964 of file vm_core.h.
VM_CALL_KW_SPLAT
#define VM_CALL_KW_SPLAT (0x01 << VM_CALL_KW_SPLAT_bit)
Definition at line 969 of file vm_core.h.
VM_CALL_KWARG
#define VM_CALL_KWARG (0x01 << VM_CALL_KWARG_bit)
Definition at line 968 of file vm_core.h.
VM_CALL_OPT_SEND
#define VM_CALL_OPT_SEND (0x01 << VM_CALL_OPT_SEND_bit)
Definition at line 972 of file vm_core.h.
VM_CALL_SUPER
#define VM_CALL_SUPER (0x01 << VM_CALL_SUPER_bit)
Definition at line 971 of file vm_core.h.
VM_CALL_TAILCALL
#define VM_CALL_TAILCALL (0x01 << VM_CALL_TAILCALL_bit)
Definition at line 970 of file vm_core.h.
VM_CALL_VCALL
#define VM_CALL_VCALL (0x01 << VM_CALL_VCALL_bit)
Definition at line 965 of file vm_core.h.
VM_CHECK_MODE
#define VM_CHECK_MODE 0
Definition at line 20 of file vm_core.h.
VM_CHECKMATCH_ARRAY
#define VM_CHECKMATCH_ARRAY 0x04
Definition at line 945 of file vm_core.h.
VM_CHECKMATCH_TYPE_MASK
#define VM_CHECKMATCH_TYPE_MASK 0x03
Definition at line 944 of file vm_core.h.
VM_DEBUG_BP_CHECK
#define VM_DEBUG_BP_CHECK 0
Definition at line 622 of file vm_core.h.
VM_DEBUG_VERIFY_METHOD_CACHE
#define VM_DEBUG_VERIFY_METHOD_CACHE (VM_DEBUG_MODE != 0)
Definition at line 626 of file vm_core.h.
VM_DEFINECLASS_FLAG_HAS_SUPERCLASS
#define VM_DEFINECLASS_FLAG_HAS_SUPERCLASS 0x10
Definition at line 876 of file vm_core.h.
VM_DEFINECLASS_FLAG_SCOPED
#define VM_DEFINECLASS_FLAG_SCOPED 0x08
Definition at line 875 of file vm_core.h.
VM_DEFINECLASS_HAS_SUPERCLASS_P
#define VM_DEFINECLASS_HAS_SUPERCLASS_P (x) ((x) & VM_DEFINECLASS_FLAG_HAS_SUPERCLASS)
Definition at line 878 of file vm_core.h.
VM_DEFINECLASS_SCOPED_P
#define VM_DEFINECLASS_SCOPED_P (x) ((x) & VM_DEFINECLASS_FLAG_SCOPED)
Definition at line 877 of file vm_core.h.
VM_DEFINECLASS_TYPE
#define VM_DEFINECLASS_TYPE (x) ((rb_vm_defineclass_type_t)(x) & VM_DEFINECLASS_TYPE_MASK)
Definition at line 874 of file vm_core.h.
VM_ENV_DATA_INDEX_ENV
#define VM_ENV_DATA_INDEX_ENV (1) /* ep[ 1] */
Definition at line 1052 of file vm_core.h.
VM_ENV_DATA_INDEX_ENV_PROC
#define VM_ENV_DATA_INDEX_ENV_PROC (2) /* ep[ 2] */
Definition at line 1053 of file vm_core.h.
VM_ENV_DATA_INDEX_FLAGS
#define VM_ENV_DATA_INDEX_FLAGS (0) /* ep[ 0] */
Definition at line 1051 of file vm_core.h.
VM_ENV_DATA_INDEX_ME_CREF
#define VM_ENV_DATA_INDEX_ME_CREF (-2) /* ep[-2] */
Definition at line 1049 of file vm_core.h.
VM_ENV_DATA_INDEX_SPECVAL
#define VM_ENV_DATA_INDEX_SPECVAL (-1) /* ep[-1] */
Definition at line 1050 of file vm_core.h.
VM_ENV_DATA_SIZE
#define VM_ENV_DATA_SIZE (3)
Definition at line 1047 of file vm_core.h.
Referenced by rb_insn_operand_intern().
VM_ENV_INDEX_LAST_LVAR
#define VM_ENV_INDEX_LAST_LVAR (-VM_ENV_DATA_SIZE)
Definition at line 1055 of file vm_core.h.
VM_GUARDED_PREV_EP
#define VM_GUARDED_PREV_EP (ep) GC_GUARDED_PTR(ep)
Definition at line 1134 of file vm_core.h.
VM_STACK_OVERFLOWED_P
#define VM_STACK_OVERFLOWED_P (cfp, sp, margin)
Value:
(!RUBY_CONST_ASSERT(sizeof(*(sp)) == sizeof(VALUE)) || \
     !RUBY_CONST_ASSERT(sizeof(*(cfp)) == sizeof(rb_control_frame_t)) || \
     ((rb_control_frame_t *)((sp) + (margin)) + 1) >= (cfp))
Definition at line 1557 of file vm_core.h.
VM_TAGGED_PTR_REF
#define VM_TAGGED_PTR_REF (v, mask) ((void *)((v) & ~mask))
Definition at line 1005 of file vm_core.h.
VM_TAGGED_PTR_SET
#define VM_TAGGED_PTR_SET (p, tag) ((VALUE)(p) | (tag))
Definition at line 1004 of file vm_core.h.
VM_UNREACHABLE
#define VM_UNREACHABLE (func) UNREACHABLE
Definition at line 54 of file vm_core.h.
VMDEBUG
#define VMDEBUG 0
VM Debug Level.
debug level: 0: no debug output 1: show instruction name 2: show stack frame when control stack frame is changed 3: show stack status 4: show register 5: 10: gc check
Definition at line 37 of file vm_core.h.
WHEN_VM_STACK_OVERFLOWED
#define WHEN_VM_STACK_OVERFLOWED (cfp, sp, margin) if (LIKELY(!VM_STACK_OVERFLOWED_P(cfp, sp, margin))) {(void)0;} else /* overflowed */
Definition at line 1561 of file vm_core.h.
Typedef Documentation
CALL_CACHE
typedef struct rb_call_cache* CALL_CACHE
Definition at line 991 of file vm_core.h.
CALL_INFO
typedef struct rb_call_info* CALL_INFO
Definition at line 990 of file vm_core.h.
CDHASH
typedef VALUE CDHASH
Definition at line 995 of file vm_core.h.
IC
typedef struct iseq_inline_cache_entry* IC
Definition at line 989 of file vm_core.h.
rb_at_exit_list
typedef struct rb_at_exit_list rb_at_exit_list
rb_backtrace_iter_func
typedef int rb_backtrace_iter_func(void *, VALUE, int, VALUE)
Definition at line 1531 of file vm_core.h.
rb_compile_option_t
typedef struct rb_compile_option_struct rb_compile_option_t
Definition at line 186 of file vm_core.h.
rb_control_frame_t
typedef struct rb_control_frame_struct rb_control_frame_t
rb_ensure_entry_t
typedef struct rb_ensure_entry rb_ensure_entry_t
rb_ensure_list_t
typedef struct rb_ensure_list rb_ensure_list_t
rb_execution_context_t
typedef struct rb_execution_context_struct rb_execution_context_t
rb_fiber_t
typedef struct rb_fiber_struct rb_fiber_t
Definition at line 738 of file vm_core.h.
rb_hook_list_t
typedef struct rb_hook_list_struct rb_hook_list_t
rb_insn_func_t
typedef rb_control_frame_t* FUNC_FASTCALL rb_insn_func_t(rb_thread_t *, rb_control_frame_t *)
Definition at line 1002 of file vm_core.h.
rb_iseq_location_t
typedef struct rb_iseq_location_struct rb_iseq_location_t
rb_jmpbuf_t
typedef RUBY_JMP_BUF rb_jmpbuf_t
Definition at line 690 of file vm_core.h.
rb_num_t
typedef unsigned long rb_num_t
Definition at line 149 of file vm_core.h.
rb_thread_id_string_t
typedef char rb_thread_id_string_t[sizeof(rb_nativethread_id_t) *2+3]
Definition at line 736 of file vm_core.h.
rb_thread_list_t
typedef struct rb_thread_list_struct rb_thread_list_t
rb_thread_t
typedef struct rb_thread_struct rb_thread_t
rb_vm_at_exit_func
typedef void rb_vm_at_exit_func(struct rb_vm_struct *)
Definition at line 497 of file vm_core.h.
rb_vm_t
typedef struct rb_vm_struct rb_vm_t
vm_call_handler
typedef VALUE(* vm_call_handler) (struct rb_thread_struct *th, struct rb_control_frame_struct *cfp, struct rb_calling_info *calling, const struct rb_call_info *ci, struct rb_call_cache *cc)
Definition at line 240 of file vm_core.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VM_FRAME_MAGIC_METHOD
VM_FRAME_MAGIC_BLOCK
VM_FRAME_MAGIC_CLASS
VM_FRAME_MAGIC_TOP
VM_FRAME_MAGIC_CFUNC
VM_FRAME_MAGIC_IFUNC
VM_FRAME_MAGIC_EVAL
VM_FRAME_MAGIC_RESCUE
VM_FRAME_MAGIC_DUMMY
VM_FRAME_MAGIC_MASK
VM_FRAME_FLAG_PASSED
VM_FRAME_FLAG_FINISH
VM_FRAME_FLAG_BMETHOD
VM_FRAME_FLAG_CFRAME
VM_FRAME_FLAG_LAMBDA
VM_ENV_FLAG_LOCAL
VM_ENV_FLAG_ESCAPED
VM_ENV_FLAG_WB_REQUIRED
Definition at line 1011 of file vm_core.h.
anonymous enum
anonymous enum
Enumerator
TIMER_INTERRUPT_MASK
PENDING_INTERRUPT_MASK
POSTPONED_JOB_INTERRUPT_MASK
TRAP_INTERRUPT_MASK
Definition at line 1598 of file vm_core.h.
method_missing_reason
enum method_missing_reason
Enumerator
MISSING_NOENTRY
MISSING_PRIVATE
MISSING_PROTECTED
MISSING_FCALL
MISSING_VCALL
MISSING_SUPER
MISSING_MISSING
MISSING_NONE
Definition at line 205 of file vm_core.h.
rb_block_handler_type
enum rb_block_handler_type
Enumerator
block_handler_type_iseq
block_handler_type_ifunc
block_handler_type_symbol
block_handler_type_proc
Definition at line 639 of file vm_core.h.
rb_block_type
enum rb_block_type
Enumerator
block_type_iseq
block_type_ifunc
block_type_symbol
block_type_proc
Definition at line 646 of file vm_core.h.
rb_thread_status
enum rb_thread_status
Enumerator
THREAD_RUNNABLE
THREAD_STOPPED
THREAD_STOPPED_FOREVER
THREAD_KILLED
Definition at line 683 of file vm_core.h.
rb_vm_defineclass_type_t
enum rb_vm_defineclass_type_t
Enumerator
VM_DEFINECLASS_TYPE_CLASS
VM_DEFINECLASS_TYPE_SINGLETON_CLASS
VM_DEFINECLASS_TYPE_MODULE
VM_DEFINECLASS_TYPE_MASK
Definition at line 866 of file vm_core.h.
ruby_basic_operators
enum ruby_basic_operators
Enumerator
BOP_PLUS
BOP_MINUS
BOP_MULT
BOP_DIV
BOP_MOD
BOP_EQ
BOP_EQQ
BOP_LT
BOP_LE
BOP_LTLT
BOP_AREF
BOP_ASET
BOP_LENGTH
BOP_SIZE
BOP_EMPTY_P
BOP_SUCC
BOP_GT
BOP_GE
BOP_NOT
BOP_NEQ
BOP_MATCH
BOP_FREEZE
BOP_UMINUS
BOP_MAX
BOP_MIN
BOP_LAST_
Definition at line 463 of file vm_core.h.
ruby_special_exceptions
enum ruby_special_exceptions
Enumerator
ruby_error_reenter
ruby_error_nomemory
ruby_error_sysstack
ruby_error_stackfatal
ruby_error_stream_closed
ruby_special_error_count
Definition at line 454 of file vm_core.h.
ruby_tag_type
enum ruby_tag_type
Enumerator
RUBY_TAG_NONE
RUBY_TAG_RETURN
RUBY_TAG_BREAK
RUBY_TAG_NEXT
RUBY_TAG_RETRY
RUBY_TAG_REDO
RUBY_TAG_RAISE
RUBY_TAG_THROW
RUBY_TAG_FATAL
RUBY_TAG_MASK
Definition at line 151 of file vm_core.h.
ruby_vm_throw_flags
enum ruby_vm_throw_flags
Enumerator
VM_THROW_NO_ESCAPE_FLAG
VM_THROW_LEVEL_SHIFT
VM_THROW_STATE_MASK
Definition at line 175 of file vm_core.h.
vm_call_flag_bits
enum vm_call_flag_bits
Enumerator
VM_CALL_ARGS_SPLAT_bit
VM_CALL_ARGS_BLOCKARG_bit
VM_CALL_FCALL_bit
VM_CALL_VCALL_bit
VM_CALL_ARGS_SIMPLE_bit
VM_CALL_BLOCKISEQ_bit
VM_CALL_KWARG_bit
VM_CALL_KW_SPLAT_bit
VM_CALL_TAILCALL_bit
VM_CALL_SUPER_bit
VM_CALL_OPT_SEND_bit
VM_CALL__END
Definition at line 947 of file vm_core.h.
vm_check_match_type
enum vm_check_match_type
Enumerator
VM_CHECKMATCH_TYPE_WHEN
VM_CHECKMATCH_TYPE_CASE
VM_CHECKMATCH_TYPE_RESCUE
Definition at line 938 of file vm_core.h.
vm_special_object_type
enum vm_special_object_type
Enumerator
VM_SPECIAL_OBJECT_VMCORE
VM_SPECIAL_OBJECT_CBASE
VM_SPECIAL_OBJECT_CONST_BASE
Definition at line 974 of file vm_core.h.
vm_svar_index
enum vm_svar_index
Enumerator
VM_SVAR_LASTLINE
VM_SVAR_BACKREF
VM_SVAR_EXTRA_START
VM_SVAR_FLIPFLOP_START
Definition at line 980 of file vm_core.h.
Function Documentation
NORETURN()
NORETURN (void rb_bug_contextconst void *, const char *fmt,...)
rb_autoloading_value()
int rb_autoloading_value (VALUE mod, ID id, VALUE * value)
Definition at line 2015 of file variable.c.
rb_binding_add_dynavars()
const VALUE* rb_binding_add_dynavars (VALUE bindval, rb_binding_t * bind, int dyncount, const ID * dynvars)
Definition at line 926 of file vm.c.
References rb_binding_t::pathobj.
rb_binding_alloc()
VALUE rb_binding_alloc (VALUE klass)
Definition at line 300 of file proc.c.
References TypedData_Make_Struct.
rb_catch_protect()
VALUE rb_catch_protect (VALUE t, rb_block_call_func * func, VALUE data, enum ruby_tag_type * stateptr)
Definition at line 2006 of file vm_eval.c.
rb_execution_context_mark()
void rb_execution_context_mark (const rb_execution_context_t * ec)
Definition at line 2371 of file vm.c.
References rb_execution_context_struct::cfp, rb_control_frame_struct::ep, rb_gc_mark_values(), rb_control_frame_struct::sp, VM_ASSERT, rb_execution_context_struct::vm_stack, and rb_execution_context_struct::vm_stack_size.
Referenced by rb_thread_mark().
rb_gc_mark_machine_stack()
void rb_gc_mark_machine_stack (const rb_execution_context_t * ec)
Definition at line 4274 of file gc.c.
References GET_STACK_BOUNDS, and rb_objspace.
rb_get_coverages()
VALUE rb_get_coverages (void)
Definition at line 5044 of file thread.c.
References GET_VM.
Referenced by rb_reset_coverages().
rb_iseq_compile()
rb_iseq_t* rb_iseq_compile (VALUE src, VALUE file, VALUE line)
Definition at line 680 of file iseq.c.
References Qnil, and rb_iseq_compile_with_option().
rb_iseq_compile_on_base()
rb_iseq_t* rb_iseq_compile_on_base (VALUE src, VALUE file, VALUE line, const struct rb_block * base_block)
Definition at line 686 of file iseq.c.
References Qnil, and rb_iseq_compile_with_option().
rb_iseq_compile_with_option()
rb_iseq_t* rb_iseq_compile_with_option (VALUE src, VALUE file, VALUE realpath, VALUE line, const struct rb_block * base_block, VALUE opt)
Definition at line 632 of file iseq.c.
References GET_THREAD, and NULL.
Referenced by rb_iseq_compile(), and rb_iseq_compile_on_base().
rb_iseq_coverage()
VALUE rb_iseq_coverage (const rb_iseq_t * iseq)
Definition at line 743 of file iseq.c.
References ISEQ_COVERAGE.
rb_iseq_disasm()
VALUE rb_iseq_disasm (const rb_iseq_t * iseq)
Definition at line 1515 of file iseq.c.
References rb_iseq_struct::body, rb_iseq_constant_body::iseq_size, rb_ary_tmp_new(), rb_secure(), rb_str_cat2(), rb_str_concat(), rb_str_new(), and size.
rb_iseq_disasm_insn()
int rb_iseq_disasm_insn (VALUE str, const VALUE * iseqval, size_t pos, const rb_iseq_t * iseq, VALUE child)
Disassemble a instruction Iseq -> Iseq inspect object.
Definition at line 1431 of file iseq.c.
References len, PRIuSIZE, rb_insn_operand_intern(), rb_str_cat2(), rb_str_catf(), rb_str_concat(), and rb_str_new().
Referenced by rb_vmdebug_debug_print_pre().
rb_iseq_eval()
RUBY_SYMBOL_EXPORT_BEGIN VALUE rb_iseq_eval (const rb_iseq_t * iseq)
Definition at line 2027 of file vm.c.
References GET_THREAD, and rb_captured_block::val.
rb_iseq_eval_main()
VALUE rb_iseq_eval_main (const rb_iseq_t * iseq)
Definition at line 2037 of file vm.c.
References GET_THREAD, and rb_captured_block::val.
rb_iseq_new()
RUBY_SYMBOL_EXPORT_BEGIN rb_iseq_t* rb_iseq_new (NODE * node, VALUE name, VALUE path, VALUE realpath, const rb_iseq_t * parent, enum iseq_type)
Definition at line 458 of file iseq.c.
References INT2FIX, and rb_iseq_new_with_opt().
Referenced by rb_vm_call_cfunc().
rb_iseq_new_main()
rb_iseq_t* rb_iseq_new_main (NODE * node, VALUE path, VALUE realpath, const rb_iseq_t * parent)
Definition at line 473 of file iseq.c.
References INT2FIX, rb_fstring_cstr(), and rb_iseq_new_with_opt().
rb_iseq_new_top()
rb_iseq_t* rb_iseq_new_top (NODE * node, VALUE name, VALUE path, VALUE realpath, const rb_iseq_t * parent)
Definition at line 466 of file iseq.c.
References INT2FIX, and rb_iseq_new_with_opt().
rb_iseq_new_with_opt()
rb_iseq_t* rb_iseq_new_with_opt (NODE * node, VALUE name, VALUE path, VALUE realpath, VALUE first_lineno, const rb_iseq_t * parent, enum iseq_type, const rb_compile_option_t *)
Definition at line 495 of file iseq.c.
References iseq_alloc().
Referenced by rb_iseq_new(), rb_iseq_new_main(), and rb_iseq_new_top().
rb_iseq_path()
VALUE rb_iseq_path (const rb_iseq_t * iseq)
Definition at line 692 of file iseq.c.
Referenced by rb_source_location(), rb_sourcefile(), rb_sourcefilename(), and rb_thread_current_status().
rb_iseq_pathobj_new()
RUBY_SYMBOL_EXPORT_END VALUE rb_iseq_pathobj_new (VALUE path, VALUE realpath)
Definition at line 217 of file iseq.c.
References NIL_P, Qnil, rb_ary_new_from_args(), rb_fstring(), rb_obj_freeze(), rb_str_cmp(), RB_TYPE_P, T_STRING, and VM_ASSERT.
Referenced by rb_iseq_pathobj_set().
rb_iseq_pathobj_set()
void rb_iseq_pathobj_set (const rb_iseq_t * iseq, VALUE path, VALUE realpath)
Definition at line 236 of file iseq.c.
References rb_iseq_struct::body, rb_iseq_constant_body::location, rb_iseq_location_struct::pathobj, rb_iseq_pathobj_new(), and RB_OBJ_WRITE.
Referenced by rb_vm_set_progname().
rb_iseq_realpath()
VALUE rb_iseq_realpath (const rb_iseq_t * iseq)
Definition at line 698 of file iseq.c.
Referenced by rb_iseq_absolute_path(), and rb_vm_set_progname().
rb_objspace_alloc()
struct rb_objspace* rb_objspace_alloc (void)
Definition at line 1327 of file gc.c.
References calloc, malloc_limit, ruby_gc_params_t::malloc_limit_min, and rb_objspace.
rb_objspace_free()
void rb_objspace_free (struct rb_objspace *)
Definition at line 1343 of file gc.c.
References free(), global_list, heap_allocated_pages, heap_eden, heap_pages_sorted, is_lazy_sweeping, list, gc_list::next, rb_objspace::profile, rb_bug(), rb_objspace::records, and xfree().
rb_postponed_job_flush()
void rb_postponed_job_flush (rb_vm_t * vm)
Definition at line 1592 of file vm_trace.c.
References ATOMIC_CAS, rb_postponed_job_struct::data, rb_thread_struct::ec, rb_execution_context_struct::errinfo, EXEC_TAG, rb_postponed_job_struct::func, GET_THREAD, rb_thread_struct::interrupt_mask, rb_vm_struct::postponed_job_buffer, rb_vm_struct::postponed_job_index, POSTPONED_JOB_INTERRUPT_MASK, Qnil, TAG_NONE, TH_POP_TAG, TH_PUSH_TAG, and TRAP_INTERRUPT_MASK.
rb_proc_alloc()
VALUE rb_proc_alloc (VALUE klass)
Definition at line 109 of file proc.c.
References TypedData_Make_Struct.
Referenced by rb_proc_create(), and rb_proc_create_from_captured().
rb_reset_coverages()
void rb_reset_coverages (void)
Definition at line 5072 of file thread.c.
References rb_get_coverages(), rb_hash_tbl_raw(), and st_foreach.
rb_set_coverages()
void rb_set_coverages (VALUE , int)
Definition at line 5050 of file thread.c.
References GET_VM, and rb_add_event_hook2().
rb_signal_buff_size()
int rb_signal_buff_size (void)
Definition at line 711 of file signal.c.
Referenced by rb_thread_check_trap_pending(), and rb_threadptr_check_signal().
rb_signal_exec()
void rb_signal_exec (rb_thread_t * th, int sig)
Definition at line 1036 of file signal.c.
References rb_vm_struct::cmd, GET_VM, Qundef, rb_interrupt(), rb_threadptr_signal_exit(), rb_threadptr_signal_raise(), rb_vm_struct::safe, SIGINT, and rb_vm_struct::trap_list.
rb_thread_alloc()
VALUE rb_thread_alloc (VALUE klass)
Definition at line 2582 of file vm.c.
rb_thread_check_trap_pending()
RUBY_SYMBOL_EXPORT_BEGIN int rb_thread_check_trap_pending (void)
Definition at line 1230 of file thread.c.
References rb_signal_buff_size().
rb_thread_method_id_and_class()
int rb_thread_method_id_and_class (rb_thread_t * th, ID * idp, ID * called_idp, VALUE * klassp)
Definition at line 2064 of file vm.c.
References rb_execution_context_struct::cfp, rb_thread_struct::ec, and rb_vm_control_frame_id_and_class().
Referenced by rb_frame_method_id_and_class(), and ruby_th_dtrace_setup().
rb_thread_reset_timer_thread()
void rb_thread_reset_timer_thread (void)
Definition at line 4078 of file thread.c.
rb_thread_start_timer_thread()
void rb_thread_start_timer_thread (void)
Definition at line 4084 of file thread.c.
rb_thread_stop_timer_thread()
void rb_thread_stop_timer_thread (void)
Definition at line 4070 of file thread.c.
rb_thread_wakeup_timer_thread()
void rb_thread_wakeup_timer_thread (void)
rb_threadptr_check_signal()
void rb_threadptr_check_signal (rb_thread_t * mth)
Definition at line 4029 of file thread.c.
References rb_signal_buff_size(), and rb_threadptr_trap_interrupt().
Referenced by ruby_cleanup().
rb_threadptr_error_print()
void rb_threadptr_error_print (rb_thread_t *volatile th, volatile VALUE errinfo)
Definition at line 167 of file eval_error.c.
References CLASS_OF, rb_thread_struct::ec, NIL_P, Qnil, Qundef, rb_execution_context_struct::raised_flag, rb_check_funcall(), rb_check_string_type(), rb_get_backtrace(), rb_intern, rb_stderr_tty_p(), rb_thread_raised_clear, RB_TYPE_P, T_STRING, TAG_NONE, TH_EXEC_TAG, TH_PUSH_TAG, and warn_print.
Referenced by rb_f_abort().
rb_threadptr_exec_event_hooks()
void rb_threadptr_exec_event_hooks (struct rb_trace_arg_struct * trace_arg)
Definition at line 370 of file vm_trace.c.
rb_threadptr_exec_event_hooks_and_pop_frame()
void rb_threadptr_exec_event_hooks_and_pop_frame (struct rb_trace_arg_struct * trace_arg)
Definition at line 364 of file vm_trace.c.
rb_threadptr_execute_interrupts()
void rb_threadptr_execute_interrupts (rb_thread_t * , int)
Definition at line 2029 of file thread.c.
References rb_thread_struct::ec, and rb_execution_context_struct::raised_flag.
Referenced by rb_thread_execute_interrupts().
rb_threadptr_interrupt()
void rb_threadptr_interrupt (rb_thread_t * th)
Definition at line 433 of file thread.c.
Referenced by rb_notify_fd_close(), and ruby_cleanup().
rb_threadptr_pending_interrupt_active_p()
int rb_threadptr_pending_interrupt_active_p (rb_thread_t * th)
Definition at line 1716 of file thread.c.
References rb_thread_struct::pending_interrupt_queue_checked.
rb_threadptr_pending_interrupt_clear()
void rb_threadptr_pending_interrupt_clear (rb_thread_t * th)
Definition at line 1589 of file thread.c.
References rb_thread_struct::pending_interrupt_queue, and rb_ary_clear().
rb_threadptr_pending_interrupt_enque()
void rb_threadptr_pending_interrupt_enque (rb_thread_t * th, VALUE v)
Definition at line 1595 of file thread.c.
References rb_thread_struct::pending_interrupt_queue, rb_thread_struct::pending_interrupt_queue_checked, and rb_ary_push().
Referenced by rb_fiber_start(), and rb_notify_fd_close().
rb_threadptr_signal_exit()
void rb_threadptr_signal_exit (rb_thread_t * th)
Definition at line 2159 of file thread.c.
References rb_eSystemExit, and rb_str_new2.
Referenced by rb_signal_exec().
rb_threadptr_signal_raise()
void rb_threadptr_signal_raise (rb_thread_t * th, int sig)
Definition at line 2149 of file thread.c.
References INT2FIX, and rb_eSignal.
Referenced by rb_signal_exec().
rb_threadptr_unlock_all_locking_mutexes()
void rb_threadptr_unlock_all_locking_mutexes (rb_thread_t * th)
Definition at line 462 of file thread.c.
References err, rb_thread_struct::keeping_mutexes, and rb_mutex_struct::next_mutex.
Referenced by rb_thread_terminate_all().
rb_vm_block_copy()
void rb_vm_block_copy (VALUE obj, const struct rb_block * dst, const struct rb_block * src)
Definition at line 831 of file vm.c.
rb_vm_block_ep_update()
void rb_vm_block_ep_update (VALUE obj, const struct rb_block * dst, const VALUE * ep)
Definition at line 271 of file vm.c.
References rb_block::as, rb_block::captured, rb_captured_block::ep, Qundef, and RB_OBJ_WRITTEN.
Referenced by rb_proc_create_from_captured().
rb_vm_bugreport()
void rb_vm_bugreport (const void *)
Definition at line 950 of file vm_dump.c.
References buf, CLASS_OF, feof, GET_VM, rb_trace_arg_struct::klass, len, LIMITED_NAME_LENGTH, rb_vm_struct::loaded_features, name, NULL, rb_vm_struct::progname, RARRAY_AREF, RARRAY_LEN, rb_backtrace_print_as_bugreport(), rb_class_real(), rb_dump_machine_register, rb_obj_class(), rb_print_backtrace(), rb_search_class_path(), RB_TYPE_P, RSTRING_PTR, SDR, T_CLASS, T_MODULE, and T_STRING.
rb_vm_call()
VALUE rb_vm_call (rb_thread_t * th, VALUE recv, VALUE id, int argc, const VALUE * argv, const rb_callable_method_entry_t * me)
Definition at line 206 of file vm_eval.c.
rb_vm_change_state()
void rb_vm_change_state (void)
rb_vm_control_frame_id_and_class()
int rb_vm_control_frame_id_and_class (const rb_control_frame_t * cfp, ID * idp, ID * called_idp, VALUE * klassp)
Definition at line 2048 of file vm.c.
References rb_callable_method_entry_struct::called_id, rb_callable_method_entry_struct::def, FALSE, rb_callable_method_entry_struct::owner, rb_vm_frame_method_entry(), and TRUE.
Referenced by rb_thread_method_id_and_class().
rb_vm_env_local_variables()
VALUE rb_vm_env_local_variables (const rb_env_t * env)
Definition at line 785 of file vm.c.
rb_vm_env_prev_env()
const rb_env_t* rb_vm_env_prev_env (const rb_env_t * env)
Definition at line 741 of file vm.c.
References rb_env_t::ep.
Referenced by rb_vmdebug_env_dump_raw().
rb_vm_ep_local_ep()
const VALUE* rb_vm_ep_local_ep (const VALUE * ep)
Definition at line 55 of file vm.c.
rb_vm_frame_block_handler()
VALUE rb_vm_frame_block_handler (const rb_control_frame_t * cfp)
Definition at line 82 of file vm.c.
Referenced by rb_block_given_p(), and rb_block_min_max_arity().
rb_vm_frame_method_entry()
const rb_callable_method_entry_t* rb_vm_frame_method_entry (const rb_control_frame_t * cfp)
Definition at line 536 of file vm_insnhelper.c.
References rb_control_frame_struct::ep.
Referenced by rb_profile_frames(), rb_thread_current_status(), rb_vm_control_frame_id_and_class(), and rb_vm_pop_cfunc_frame().
rb_vm_get_binding_creatable_next_cfp()
rb_control_frame_t* rb_vm_get_binding_creatable_next_cfp (const rb_thread_t * th, const rb_control_frame_t * cfp)
Definition at line 486 of file vm.c.
References rb_control_frame_struct::iseq, RUBY_VM_CONTROL_FRAME_STACK_OVERFLOW_P, and RUBY_VM_PREVIOUS_CONTROL_FRAME.
Referenced by rb_tracearg_binding(), rb_vm_make_binding(), and rb_vm_stack_to_heap().
rb_vm_get_ruby_level_next_cfp()
rb_control_frame_t* rb_vm_get_ruby_level_next_cfp (const rb_thread_t * th, const rb_control_frame_t * cfp)
Definition at line 498 of file vm.c.
References RUBY_VM_CONTROL_FRAME_STACK_OVERFLOW_P.
Referenced by rb_source_location(), rb_sourcefile(), rb_sourcefilename(), rb_sourceline(), rb_vm_cbase(), rb_vm_cref(), rb_vm_cref_in_context(), rb_vm_cref_replace_with_duplicated_cref(), and rb_vm_make_binding().
rb_vm_get_sourceline()
int rb_vm_get_sourceline (const rb_control_frame_t *)
Definition at line 38 of file vm_backtrace.c.
Referenced by rb_source_location(), rb_sourceline(), and rb_thread_current_status().
rb_vm_gvl_destroy()
void rb_vm_gvl_destroy (rb_vm_t * vm)
Definition at line 348 of file thread.c.
References rb_vm_struct::thread_destruct_lock.
rb_vm_inc_const_missing_count()
void rb_vm_inc_const_missing_count (void)
Definition at line 330 of file vm.c.
References rb_class_path_no_cache().
rb_vm_invoke_proc()
VALUE rb_vm_invoke_proc (rb_thread_t * th, rb_proc_t * proc, int argc, const VALUE * argv, VALUE block_handler)
Definition at line 1172 of file vm.c.
Referenced by rb_fiber_start(), rb_proc_call(), and rb_proc_call_with_block().
rb_vm_make_binding()
VALUE rb_vm_make_binding (rb_thread_t * th, const rb_control_frame_t * src_cfp)
Definition at line 895 of file vm.c.
References rb_eRuntimeError, rb_raise(), rb_vm_get_binding_creatable_next_cfp(), and rb_vm_get_ruby_level_next_cfp().
Referenced by rb_binding_new(), and rb_tracearg_binding().
rb_vm_make_proc()
VALUE rb_vm_make_proc (rb_thread_t * th, const struct rb_captured_block * captured, VALUE klass)
Definition at line 868 of file vm.c.
References FALSE, and rb_vm_make_proc_lambda().
rb_vm_make_proc_lambda()
VALUE rb_vm_make_proc_lambda (rb_thread_t * th, const struct rb_captured_block * captured, VALUE klass, int8_t is_lambda)
Definition at line 874 of file vm.c.
Referenced by rb_vm_make_proc().
rb_vm_pop_frame()
void rb_vm_pop_frame (rb_thread_t * th)
Definition at line 302 of file vm_insnhelper.c.
rb_vm_proc_local_ep()
const VALUE* rb_vm_proc_local_ep (VALUE proc)
Definition at line 565 of file thread.c.
Referenced by rb_fiber_start().
rb_vm_register_special_exception_str()
void rb_vm_register_special_exception_str (enum ruby_special_exceptions sp, VALUE exception_class, VALUE mesg)
Definition at line 2161 of file vm.c.
References GET_VM, OBJ_FREEZE, OBJ_TAINT, rb_exc_new3, rb_gc_register_mark_object(), rb_obj_freeze(), and rb_vm_struct::special_exceptions.
rb_vm_rewind_cfp()
void rb_vm_rewind_cfp (rb_thread_t * th, rb_control_frame_t * cfp)
Definition at line 544 of file vm.c.
References rb_execution_context_struct::cfp, and rb_thread_struct::ec.
rb_vm_rewrite_cref()
void rb_vm_rewrite_cref (rb_cref_t * node, VALUE old_klass, VALUE new_klass, rb_cref_t ** new_cref_ptr)
Definition at line 713 of file vm_insnhelper.c.
rb_vm_stack_to_heap()
void rb_vm_stack_to_heap (rb_thread_t * th)
Definition at line 731 of file vm.c.
References rb_execution_context_struct::cfp, rb_thread_struct::ec, and rb_vm_get_binding_creatable_next_cfp().
rb_vmdebug_debug_print_post()
void rb_vmdebug_debug_print_post (rb_thread_t * th, rb_control_frame_t * cfp)
Definition at line 362 of file vm_dump.c.
References rb_execution_context_struct::cfp, rb_thread_struct::ec, rb_inspect(), rb_vmdebug_debug_print_register(), SDR2, and StringValueCStr.
rb_vmdebug_debug_print_pre()
void rb_vmdebug_debug_print_pre (rb_thread_t * th, rb_control_frame_t * cfp, const VALUE * _pc)
Definition at line 333 of file vm_dump.c.
References rb_iseq_struct::body, rb_thread_struct::ec, rb_control_frame_struct::iseq, rb_iseq_constant_body::iseq_encoded, rb_iseq_disasm_insn(), rb_iseq_original_iseq(), rb_vmdebug_debug_print_register(), rb_control_frame_struct::sp, VM_CFP_CNT, and rb_execution_context_struct::vm_stack.
rb_vmdebug_stack_dump_raw()
void rb_vmdebug_stack_dump_raw (rb_thread_t * , rb_control_frame_t *)
Definition at line 141 of file vm_dump.c.
References rb_thread_struct::ec, rb_control_frame_struct::ep, GC_GUARDED_PTR_REF, PRIxVALUE, rb_control_frame_struct::sp, rb_execution_context_struct::vm_stack, and rb_execution_context_struct::vm_stack_size.
Referenced by rb_vmdebug_stack_dump_all_threads(), and rb_vmdebug_stack_dump_raw_current().
ruby_node_name()
const char* ruby_node_name (int node)
Definition at line 1767 of file iseq.c.
References rb_bug().
Referenced by ruby_debug_print_node().
ruby_thread_init_stack()
void ruby_thread_init_stack (rb_thread_t * th)
Definition at line 559 of file thread.c.
STATIC_ASSERT() [1/2]
STATIC_ASSERT (rb_vm_tag_buf_offset , offsetof(struct rb_vm_tag, buf) , 0)
STATIC_ASSERT() [2/2]
STATIC_ASSERT (rb_vm_tag_buf_end)
Variable Documentation
rb_cISeq
RUBY_EXTERN VALUE rb_cISeq
Definition at line 902 of file vm_core.h.
rb_cRubyVM
RUBY_EXTERN VALUE rb_cRubyVM
Definition at line 903 of file vm_core.h.
rb_mRubyVMFrozenCore
RUBY_EXTERN VALUE rb_mRubyVMFrozenCore
Definition at line 904 of file vm_core.h.
ruby_binding_data_type
const rb_data_type_t ruby_binding_data_type
Definition at line 289 of file proc.c.
ruby_current_thread
RUBY_SYMBOL_EXPORT_BEGIN rb_thread_t* ruby_current_thread
Definition at line 320 of file vm.c.
ruby_current_vm
rb_vm_t* ruby_current_vm
Definition at line 321 of file vm.c.
ruby_threadptr_data_type
const rb_data_type_t ruby_threadptr_data_type
Definition at line 2495 of file vm.c.
ruby_vm_event_flags
rb_event_flag_t ruby_vm_event_flags
Definition at line 322 of file vm.c.