Ruby: ext/socket/ipsocket.c File Reference
ipsocket.c File Reference
#include "rubysocket.h"
Data Structures
struct inetsock_arg
Macros
#define return_norevlookup(x) {*norevlookup = (x); return 1;}
Functions
VALUE rsock_init_inetsock (VALUE sock, VALUE remote_host, VALUE remote_serv, VALUE local_host, VALUE local_serv, int type)
int rsock_revlookup_flag (VALUE revlookup, int *norevlookup)
void rsock_init_ipsocket (void)
Macro Definition Documentation
return_norevlookup
#define return_norevlookup (x) {*norevlookup = (x); return 1;}
Referenced by rsock_revlookup_flag().
Function Documentation
rsock_init_inetsock()
VALUE rsock_init_inetsock (VALUE sock, VALUE remote_host, VALUE remote_serv, VALUE local_host, VALUE local_serv, int type)
Definition at line 152 of file ipsocket.c.
References inetsock_arg::fd, inetsock_arg::host, inetsock_arg::local, rb_ensure(), inetsock_arg::remote, inetsock_arg::res, inetsock_arg::serv, inetsock_arg::sock, and inetsock_arg::type.
rsock_init_ipsocket()
void rsock_init_ipsocket (void)
Definition at line 364 of file ipsocket.c.
References rb_cBasicSocket, rb_cIPSocket, rb_define_class(), and rb_define_method().
Referenced by rsock_init_socket_init().
rsock_revlookup_flag()
int rsock_revlookup_flag (VALUE revlookup, int * norevlookup)
Definition at line 172 of file ipsocket.c.
References Check_Type, id, Qfalse, Qnil, Qtrue, return_norevlookup, SYM2ID, and T_SYMBOL.