Ruby: ext/fiddle/function.h File Reference
function.h File Reference
#include <fiddle.h>
Functions
void Init_fiddle_function (void)
Function Documentation
Init_fiddle_function()
void Init_fiddle_function (void)
Definition at line 232 of file function.c.
References cFiddleFunction, INT2NUM, mFiddle, rb_cObject, rb_define_alloc_func(), rb_define_class_under(), and rb_define_const().