Ruby: ext/openssl/ossl_pkey.c File Reference
ossl_pkey.c File Reference
#include "ossl.h"
Functions
int ossl_generate_cb_2 (int p, int n, BN_GENCB *cb)
void ossl_generate_cb_stop (void *ptr)
VALUE ossl_pkey_new (EVP_PKEY *pkey)
EVP_PKEY * GetPKeyPtr (VALUE obj)
EVP_PKEY * GetPrivPKeyPtr (VALUE obj)
EVP_PKEY * DupPKeyPtr (VALUE obj)
void Init_ossl_pkey (void)
Variables
VALUE mPKey
VALUE cPKey
VALUE ePKeyError
const rb_data_type_t ossl_evp_pkey_type
Function Documentation
DupPKeyPtr()
EVP_PKEY* DupPKeyPtr (VALUE obj)
Definition at line 229 of file ossl_pkey.c.
References EVP_PKEY_up_ref, and GetPKey.
GetPKeyPtr()
EVP_PKEY* GetPKeyPtr (VALUE obj)
Definition at line 206 of file ossl_pkey.c.
References GetPKey.
GetPrivPKeyPtr()
EVP_PKEY* GetPrivPKeyPtr (VALUE obj)
Definition at line 216 of file ossl_pkey.c.
References rb_funcallv.
Init_ossl_pkey()
void Init_ossl_pkey (void)
Definition at line 389 of file ossl_pkey.c.
References cPKey, eOSSLError, ePKeyError, mOSSL, mPKey, rb_cObject, rb_define_class_under(), rb_define_module(), rb_define_module_function(), rb_define_module_under(), and rb_eStandardError.
ossl_generate_cb_2()
int ossl_generate_cb_2 (int p, int n, BN_GENCB * cb)
Definition at line 24 of file ossl_pkey.c.
References BN_GENCB_get_arg, INT2NUM, rb_ary_new2, rb_ary_store(), rb_protect(), rb_yield(), ossl_generate_cb_arg::state, ossl_generate_cb_arg::stop, and ossl_generate_cb_arg::yield.
ossl_generate_cb_stop()
void ossl_generate_cb_stop (void * ptr)
Definition at line 50 of file ossl_pkey.c.
References ossl_generate_cb_arg::stop.
ossl_pkey_new()
VALUE ossl_pkey_new (EVP_PKEY * pkey)
Definition at line 107 of file ossl_pkey.c.
References rb_protect().
Variable Documentation
cPKey
VALUE cPKey
Definition at line 16 of file ossl_pkey.c.
Referenced by Init_ossl_dh(), Init_ossl_dsa(), Init_ossl_ec(), Init_ossl_pkey(), and Init_ossl_rsa().
ePKeyError
VALUE ePKeyError
Definition at line 17 of file ossl_pkey.c.
Referenced by Init_ossl_dh(), Init_ossl_dsa(), Init_ossl_ec(), Init_ossl_pkey(), and Init_ossl_rsa().
mPKey
VALUE mPKey
Definition at line 15 of file ossl_pkey.c.
Referenced by Init_ossl_dh(), Init_ossl_dsa(), Init_ossl_ec(), Init_ossl_pkey(), and Init_ossl_rsa().
ossl_evp_pkey_type
const rb_data_type_t ossl_evp_pkey_type
Initial value:
= {
    "OpenSSL/EVP_PKEY",
    {
        0, ossl_evp_pkey_free,
    },
    0, 0, RUBY_TYPED_FREE_IMMEDIATELY,
}
Definition at line 65 of file ossl_pkey.c.