Ruby: bug_reporters Struct Reference
bug_reporters Struct Reference
Exception handlings
Data Fields
void(* func)(FILE *out, void *data)
void * data
Detailed Description
Definition at line 345 of file error.c.
Field Documentation
data
void* bug_reporters::data
Definition at line 347 of file error.c.
Referenced by bug_report_end(), rb_bug_reporter_add(), and syserr_initialize().
func
void(* bug_reporters::func) (FILE *out, void *data)
Definition at line 346 of file error.c.
Referenced by bug_report_end(), rb_bug_reporter_add(), and syserr_initialize().
The documentation for this struct was generated from the following file:
error.c (60185)