Ruby: ext/openssl/ossl_bio.c File Reference
ossl_bio.c File Reference
#include "ossl.h"
Functions
BIO * ossl_obj2bio (volatile VALUE *pobj)
VALUE ossl_membio2str (BIO *bio)
Function Documentation
ossl_membio2str()
VALUE ossl_membio2str (BIO * bio)
Definition at line 29 of file ossl_bio.c.
References buf, ossl_str_new(), and rb_jump_tag().
ossl_obj2bio()
BIO* ossl_obj2bio (volatile VALUE * pobj)
Definition at line 13 of file ossl_bio.c.
References eOSSLError, NULL, ossl_raise(), rb_funcallv, rb_intern, RB_TYPE_P, RSTRING_LENINT, RSTRING_PTR, StringValue, and T_FILE.
Referenced by DupConfigPtr().