Ruby: ext/psych/psych_emitter.c File Reference
psych_emitter.c File Reference
#include <psych.h>
Functions
void Init_psych_emitter (void)
Variables
VALUE cPsychEmitter
Function Documentation
Init_psych_emitter()
void Init_psych_emitter (void)
Definition at line 522 of file psych_emitter.c.
References cPsychEmitter, rb_cObject, rb_define_alloc_func(), rb_define_class_under(), and rb_define_module().
Variable Documentation
cPsychEmitter
VALUE cPsychEmitter
Definition at line 10 of file psych_emitter.c.
Referenced by Init_psych_emitter().