Ruby: ext/win32ole/win32ole_type.h File Reference
win32ole_type.h File Reference
Functions
VALUE create_win32ole_type (ITypeInfo *pTypeInfo, VALUE name)
ITypeInfo * itypeinfo (VALUE self)
VALUE ole_type_from_itypeinfo (ITypeInfo *pTypeInfo)
void Init_win32ole_type (void)
Variables
VALUE cWIN32OLE_TYPE
Function Documentation
create_win32ole_type()
VALUE create_win32ole_type (ITypeInfo * pTypeInfo, VALUE name)
Definition at line 207 of file win32ole_type.c.
Referenced by ole_type_from_itypeinfo().
Init_win32ole_type()
void Init_win32ole_type (void)
Definition at line 886 of file win32ole_type.c.
References cWIN32OLE_TYPE, rb_cObject, rb_define_class(), and rb_define_singleton_method().
itypeinfo()
ITypeInfo* itypeinfo (VALUE self)
Definition at line 76 of file win32ole_type.c.
References oletypedata::pTypeInfo, and TypedData_Get_Struct.
ole_type_from_itypeinfo()
VALUE ole_type_from_itypeinfo (ITypeInfo * pTypeInfo)
Definition at line 84 of file win32ole_type.c.
References create_win32ole_type(), HRESULT(), NULL, OLE_RELEASE, Qnil, and WC2VSTR.
Variable Documentation
cWIN32OLE_TYPE
VALUE cWIN32OLE_TYPE
Definition at line 3 of file win32ole_type.h.
Referenced by Init_win32ole_type().