Ruby: vm_debug.h File Reference
vm_debug.h File Reference
#include "ruby/ruby.h"
#include "node.h"
Macros
#define dpv(h, v) ruby_debug_print_value(-1, 0, (h), (v))
#define dp(v) ruby_debug_print_value(-1, 0, "", (v))
#define dpi(i) ruby_debug_print_id(-1, 0, "", (i))
#define dpn(n) ruby_debug_print_node(-1, 0, "", (n))
#define bp() ruby_debug_breakpoint()
Functions
VALUE ruby_debug_print_value (int level, int debug_level, const char *header, VALUE v)
ID ruby_debug_print_id (int level, int debug_level, const char *header, ID id)
NODE * ruby_debug_print_node (int level, int debug_level, const char *header, const NODE *node)
int ruby_debug_print_indent (int level, int debug_level, int indent_level)
void ruby_debug_breakpoint (void)
void ruby_debug_gc_check_func (void)
void ruby_set_debug_option (const char *str)
Macro Definition Documentation
bp
#define bp () ruby_debug_breakpoint()
Definition at line 25 of file vm_debug.h.
Referenced by onig_is_code_in_cc(), onig_vsnprintf_with_pattern(), and rb_str_include_range_p().
dp
#define dp (v) ruby_debug_print_value(-1, 0, "", (v))
Definition at line 21 of file vm_debug.h.
Referenced by rb_absint_singlebit_p(), rb_absint_size(), and rb_econv_append().
dpi
#define dpi (i) ruby_debug_print_id(-1, 0, "", (i))
Definition at line 22 of file vm_debug.h.
dpn
#define dpn (n) ruby_debug_print_node(-1, 0, "", (n))
Definition at line 23 of file vm_debug.h.
dpv
#define dpv (h, v) ruby_debug_print_value(-1, 0, (h), (v))
Definition at line 20 of file vm_debug.h.
Function Documentation
ruby_debug_breakpoint()
void ruby_debug_breakpoint (void)
Definition at line 126 of file debug.c.
References ruby_rgengc_debug.
ruby_debug_gc_check_func()
void ruby_debug_gc_check_func (void)
ruby_debug_print_id()
ID ruby_debug_print_id (int level, int debug_level, const char * header, ID id)
Definition at line 106 of file debug.c.
References id, and rb_id2name().
ruby_debug_print_indent()
int ruby_debug_print_indent (int level, int debug_level, int indent_level)
Definition at line 65 of file debug.c.
References FALSE, and TRUE.
ruby_debug_print_node()
NODE* ruby_debug_print_node (int level, int debug_level, const char * header, const NODE * node)
Definition at line 116 of file debug.c.
References nd_line, nd_type, and ruby_node_name().
ruby_debug_print_value()
VALUE ruby_debug_print_value (int level, int debug_level, const char * header, VALUE v)
Definition at line 87 of file debug.c.
References rb_raw_obj_info().
Referenced by ruby_debug_print_v().
ruby_set_debug_option()
void ruby_set_debug_option (const char * str)
Definition at line 215 of file debug.c.
References ruby_each_words().
Referenced by main().