Ruby: ext/digest/sha1/sha1init.c File Reference
sha1init.c File Reference
#include <ruby/ruby.h>
#include "../digest.h"
#include "sha1.h"
Macros
#define RUBY_UNTYPED_DATA_WARNING 0
Functions
void Init_sha1 (void)
Macro Definition Documentation
RUBY_UNTYPED_DATA_WARNING
#define RUBY_UNTYPED_DATA_WARNING 0
Function Documentation
Init_sha1()
void Init_sha1 (void)
Definition at line 52 of file sha1init.c.
References Data_Wrap_Struct, rb_define_class_under(), rb_define_module(), rb_iv_set(), rb_path2class(), and rb_require().