Ruby: ext/socket/constdefs.c File Reference
constdefs.c File Reference
Macros
#define INTEGER2NUM(n)
Functions
int rsock_family_to_int (const char *str, long len, int *valp)
int rsock_socktype_to_int (const char *str, long len, int *valp)
int rsock_ipproto_to_int (const char *str, long len, int *valp)
int rsock_unknown_level_to_int (const char *str, long len, int *valp)
int rsock_ip_level_to_int (const char *str, long len, int *valp)
int rsock_so_optname_to_int (const char *str, long len, int *valp)
int rsock_ip_optname_to_int (const char *str, long len, int *valp)
int rsock_tcp_optname_to_int (const char *str, long len, int *valp)
int rsock_udp_optname_to_int (const char *str, long len, int *valp)
int rsock_shutdown_how_to_int (const char *str, long len, int *valp)
int rsock_scm_optname_to_int (const char *str, long len, int *valp)
ID rsock_intern_family (int val)
ID rsock_intern_family_noprefix (int val)
ID rsock_intern_protocol_family (int val)
ID rsock_intern_socktype (int val)
ID rsock_intern_ipproto (int val)
ID rsock_intern_iplevel (int val)
ID rsock_intern_so_optname (int val)
ID rsock_intern_ip_optname (int val)
ID rsock_intern_ipv6_optname (int val)
ID rsock_intern_tcp_optname (int val)
ID rsock_intern_udp_optname (int val)
ID rsock_intern_scm_optname (int val)
ID rsock_intern_local_optname (int val)
Macro Definition Documentation
INTEGER2NUM
#define INTEGER2NUM (n)
Value:
(FIXNUM_MAX < (n) ? ULONG2NUM(n) : \
     FIXNUM_MIN > (long)(n) ? LONG2NUM(n) : \
     LONG2FIX(n))
Definition at line 23 of file constdefs.c.
Function Documentation
rsock_family_to_int()
int rsock_family_to_int (const char * str, long len, int * valp)
Definition at line 4468 of file constdefs.c.
References AF_UNSPEC, memcmp(), PF_INET, and PF_UNSPEC.
rsock_intern_family()
ID rsock_intern_family (int val)
Definition at line 6736 of file constdefs.c.
References name, st_data_t, and st_lookup.
Referenced by rsock_inspect_sockaddr(), and rsock_ipaddr().
rsock_intern_family_noprefix()
ID rsock_intern_family_noprefix (int val)
Definition at line 6745 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_ip_optname()
ID rsock_intern_ip_optname (int val)
Definition at line 6799 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_iplevel()
ID rsock_intern_iplevel (int val)
Definition at line 6781 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_ipproto()
ID rsock_intern_ipproto (int val)
Definition at line 6772 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_ipv6_optname()
ID rsock_intern_ipv6_optname (int val)
Definition at line 6808 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_local_optname()
ID rsock_intern_local_optname (int val)
Definition at line 6844 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_protocol_family()
ID rsock_intern_protocol_family (int val)
Definition at line 6754 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_scm_optname()
ID rsock_intern_scm_optname (int val)
Definition at line 6835 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_so_optname()
ID rsock_intern_so_optname (int val)
Definition at line 6790 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_socktype()
ID rsock_intern_socktype (int val)
Definition at line 6763 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_tcp_optname()
ID rsock_intern_tcp_optname (int val)
Definition at line 6817 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_intern_udp_optname()
ID rsock_intern_udp_optname (int val)
Definition at line 6826 of file constdefs.c.
References name, st_data_t, and st_lookup.
rsock_ip_level_to_int()
int rsock_ip_level_to_int (const char * str, long len, int * valp)
Definition at line 5162 of file constdefs.c.
References IPPROTO_ICMP, IPPROTO_IP, IPPROTO_RAW, IPPROTO_TCP, IPPROTO_UDP, and memcmp().
rsock_ip_optname_to_int()
int rsock_ip_optname_to_int (const char * str, long len, int * valp)
Definition at line 5815 of file constdefs.c.
References len, and memcmp().
rsock_ipproto_to_int()
int rsock_ipproto_to_int (const char * str, long len, int * valp)
Definition at line 4932 of file constdefs.c.
References IPPROTO_ICMP, IPPROTO_IP, IPPROTO_RAW, IPPROTO_TCP, IPPROTO_UDP, and memcmp().
rsock_scm_optname_to_int()
int rsock_scm_optname_to_int (const char * str, long len, int * valp)
Definition at line 6641 of file constdefs.c.
References memcmp().
rsock_shutdown_how_to_int()
int rsock_shutdown_how_to_int (const char * str, long len, int * valp)
Definition at line 6601 of file constdefs.c.
References memcmp(), SHUT_RD, SHUT_RDWR, and SHUT_WR.
rsock_so_optname_to_int()
int rsock_so_optname_to_int (const char * str, long len, int * valp)
Definition at line 5376 of file constdefs.c.
References memcmp().
rsock_socktype_to_int()
int rsock_socktype_to_int (const char * str, long len, int * valp)
Definition at line 4862 of file constdefs.c.
References memcmp().
rsock_tcp_optname_to_int()
int rsock_tcp_optname_to_int (const char * str, long len, int * valp)
Definition at line 6359 of file constdefs.c.
References memcmp().
rsock_udp_optname_to_int()
int rsock_udp_optname_to_int (const char * str, long len, int * valp)
Definition at line 6579 of file constdefs.c.
References memcmp().
rsock_unknown_level_to_int()
int rsock_unknown_level_to_int (const char * str, long len, int * valp)
Definition at line 5140 of file constdefs.c.
References memcmp().