Ruby: ext/win32ole/win32ole_method.c File Reference
win32ole_method.c File Reference
#include "win32ole.h"
Functions
struct olemethoddata * olemethod_data_get_struct (VALUE obj)
VALUE ole_methods_from_typeinfo (ITypeInfo *pTypeInfo, int mask)
VALUE create_win32ole_method (ITypeInfo *pTypeInfo, VALUE name)
VALUE folemethod_s_allocate (VALUE klass)
void Init_win32ole_method (void)
Function Documentation
create_win32ole_method()
VALUE create_win32ole_method (ITypeInfo * pTypeInfo, VALUE name)
Definition at line 210 of file win32ole_method.c.
References cWIN32OLE_METHOD, and folemethod_s_allocate().
folemethod_s_allocate()
VALUE folemethod_s_allocate (VALUE klass)
Definition at line 239 of file win32ole_method.c.
References olemethoddata::index, NULL, olemethoddata::pOwnerTypeInfo, olemethoddata::pTypeInfo, and TypedData_Make_Struct.
Referenced by create_win32ole_method(), and Init_win32ole_method().
Init_win32ole_method()
void Init_win32ole_method (void)
Definition at line 926 of file win32ole_method.c.
References cWIN32OLE_METHOD, folemethod_s_allocate(), rb_cObject, rb_define_alloc_func(), rb_define_class(), and rb_define_method().
ole_methods_from_typeinfo()
VALUE ole_methods_from_typeinfo (ITypeInfo * pTypeInfo, int mask)
Definition at line 112 of file win32ole_method.c.
References eWIN32OLERuntimeError, HRESULT(), OLE_GET_TYPEATTR, ole_raise(), and rb_ary_new().
olemethod_data_get_struct()
struct olemethoddata* olemethod_data_get_struct (VALUE obj)
Definition at line 67 of file win32ole_method.c.
References TypedData_Get_Struct.