Ruby: ext/psych/psych_yaml_tree.c File Reference
psych_yaml_tree.c File Reference
#include <psych.h>
Functions
void Init_psych_yaml_tree (void)
Variables
VALUE cPsychVisitorsYamlTree
Function Documentation
Init_psych_yaml_tree()
void Init_psych_yaml_tree (void)
Definition at line 15 of file psych_yaml_tree.c.
References cPsychVisitorsYamlTree, rb_cObject, rb_define_class_under(), rb_define_module(), rb_define_module_under(), and rb_define_private_method().
Variable Documentation
cPsychVisitorsYamlTree
VALUE cPsychVisitorsYamlTree
Definition at line 3 of file psych_yaml_tree.c.
Referenced by Init_psych_yaml_tree().