Ruby: ext/psych/psych_parser.h File Reference
psych_parser.h File Reference
Functions
void Init_psych_parser (void)
Function Documentation
Init_psych_parser()
void Init_psych_parser (void)
Definition at line 527 of file psych_parser.c.
References cPsychParser, mPsych, rb_cObject, rb_define_alloc_func(), rb_define_class_under(), and rb_define_module().