Ruby: ext/rbconfig/sizeof/limits.c File Reference
limits.c File Reference
#include <limits.h>
#include "ruby/ruby.h"
Macros
#define MAX2NUM(name) ULONG2NUM(name ## _MAX)
#define MIN2NUM(name) LONG2NUM(name ## _MIN)
#define DEFINE(k, v) rb_hash_aset(h, rb_str_new_cstr(#k), v)
Functions
void Init_limits (void)
Macro Definition Documentation
DEFINE
#define DEFINE (k, v) rb_hash_aset(h, rb_str_new_cstr(#k), v)
Referenced by Init_limits().
MAX2NUM
#define MAX2NUM (name) ULONG2NUM(name ## _MAX)
Referenced by Init_limits().
MIN2NUM
#define MIN2NUM (name) LONG2NUM(name ## _MIN)
Referenced by Init_limits().
Function Documentation
Init_limits()
void Init_limits (void)
Definition at line 14 of file limits.c.
References DEFINE, FIXNUM_MAX, FIXNUM_MIN, LONG_MAX, LONG_MIN, MAX2NUM, MIN2NUM, rb_define_const(), rb_define_module(), and rb_hash_new().
Referenced by Init_sizeof().